### PR TITLE
Added snippet to enable/disable wifi-verbose logging on API 21+

### PR DESCRIPTION
**Pull request by whutchin5**
Added an RPC to enable or disable wifi-verbose logging. Only available on API 21+.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/46)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 232 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAZq9QblHjh0OoTKW-:-KjAZq9QblHjh0OoTKW0:bfncs8m) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/e739533c802b7ed1ba7fa82cb164c2ed34abfbd8/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L232)):*
> ```Java
>     @TargetApi(21)
>     @Rpc(description = "Enable or disable wifi verbose logging.")
>     public void setWifiVerboseLogging(boolean enabled) throws Throwable {
> ```

"enable" instead of "enabled"

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 238 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAZffSlRnByqjISUf1:-KjAZffSlRnByqjISUf2:bpb5d62) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/e739533c802b7ed1ba7fa82cb164c2ed34abfbd8/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L238)):*
> ```Java
>                     .getDeclaredMethod("enableVerboseLogging", int.class)
>                     .invoke(mWifiManager, enabled ? 1 : 0);
>         } catch (NoSuchMethodException | InvocationTargetException e) {
> ```

should we catch `NoSuchMethodException` here?
Isn't throwing the ret value of getCause specific to `InvocationTargetException`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 238 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAZffSlRnByqjISUf1:-KjAarBGYR5rwgGFgf4n:b-hkzzue) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/e739533c802b7ed1ba7fa82cb164c2ed34abfbd8/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L238)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should we catch `NoSuchMethodException` here?
Isn't throwing the ret value of getCause specific to `InvocationTargetException`?
</blockquote></details>

Please hold off on this; there's a simplified reflection API coming up in https://github.com/google/mobly-bundled-snippets/pull/45 which will mean we don't have to handle any of this ourselves anymore so the extra wrapping will just go away. :)

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 230 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAaZZld3M2BVQU0p8H:-KjAaZZld3M2BVQU0p8I:bf4ctj) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/6ce6cac669cb2f3b8eca9edb3bdc41dedd0ee063/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L230)):*
> ```Java
>     }
> 
>     @TargetApi(21)
> ```

Could you use RpcMinSdk instead of TargetApi? RpcMinSdk is actually checked by the snippet server when triggering an RPC so we'll get a much better error. (TargetApi is only checked by build tools and is not available at runtime so we'd just get a NoSuchMethodException).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 238 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAZffSlRnByqjISUf1:-KjB9aykTxcZn_W3b30V:b-jeb1z9) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/e739533c802b7ed1ba7fa82cb164c2ed34abfbd8/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L238)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Please hold off on this; there's a simplified reflection API coming up in https://github.com/google/mobly-bundled-snippets/pull/45 which will mean we don't have to handle any of this ourselves anymore so the extra wrapping will just go away. :)
</blockquote></details>

The [reflection api change](https://github.com/google/mobly-bundled-snippets/pull/45/files) has been submitted, so you can port to using that API now:

```
Utils.invokeByReflection(mWifiManager, "enableVerboseLogging", enable ? 1 : 0);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46)*

**Comment by xpconanfan** [comment]
Could you run the linter `./gradlew goJF`

**Comment by whutchin5** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 232 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAZq9QblHjh0OoTKW-:-KjEfFgrSJ_xMTk_5gP1:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/e739533c802b7ed1ba7fa82cb164c2ed34abfbd8/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L232)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"enable" instead of "enabled"
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 238 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAZffSlRnByqjISUf1:-KjEfGYo51lGdOC5zIYO:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/e739533c802b7ed1ba7fa82cb164c2ed34abfbd8/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L238)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

The [reflection api change](https://github.com/google/mobly-bundled-snippets/pull/45/files) has been submitted, so you can port to using that API now:

```
Utils.invokeByReflection(mWifiManager, "enableVerboseLogging", enable ? 1 : 0);
```
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 230 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjAaZZld3M2BVQU0p8H:-KjEfEzwx1qxBXUf8lzv:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/6ce6cac669cb2f3b8eca9edb3bdc41dedd0ee063/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L230)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Could you use RpcMinSdk instead of TargetApi? RpcMinSdk is actually checked by the snippet server when triggering an RPC so we'll get a much better error. (TargetApi is only checked by build tools and is not available at runtime so we'd just get a NoSuchMethodException).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46)*

**Comment by whutchin5** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-:-KjF2Puvx4VaM2QG__zu:bs7wumb)*

**Comment by adorokhine** [comment]
:lgtm: Leaving final approval to Ang.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-:-KjF7VrnLYe24Lb-H44x:b-yd19mn)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 229 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjF7d1xqq3aUz5AxOQ0:-KjF7d1xqq3aUz5AxOQ1:b-q2p579) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/976f4e4df7c92f7cf67a29092bec218addf06ff5/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L229)):*
> ```Java
>     @RpcMinSdk(Build.VERSION_CODES.LOLLIPOP)
>     @Rpc(description = "Enable or disable wifi verbose logging.")
>     public void setWifiVerboseLogging(boolean enable) throws Throwable {
> ```

@Ang Per our naming convention this should actually be wifiSetVerboseLogging right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 229 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjF7d1xqq3aUz5AxOQ0:-KjF8k1k_OU2Jxe-Y8Zg:b-vuqqji) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/976f4e4df7c92f7cf67a29092bec218addf06ff5/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L229)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

@Ang Per our naming convention this should actually be wifiSetVerboseLogging right?
</blockquote></details>

Yes, pls change to `wifiSetVerboseLogging`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46)*

**Comment by whutchin5** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-:-KjFA6HB_69X91RZZvMX:b-896fix)*

**Comment by whutchin5** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 229 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46#-KjF7d1xqq3aUz5AxOQ0:-KjFAFcNQJlZaAa0D4xw:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/976f4e4df7c92f7cf67a29092bec218addf06ff5/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L229)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Yes, pls change to `wifiSetVerboseLogging`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/46)*

**Pull request merged**
