### PR TITLE
Do not attempt to modify a network in wifiConnect.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/68)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 206 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68#-Kp0plg8pRBhHunPVJzg:-Kp0plg8pRBhHunPVJzh:b-3zhz0e) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f1ae9d6daa5f6dd5fa43266f6bd13dbd4de8d74c/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L206)):*
> ```Java
>         // We have to do this because in N+, network configs can only be modified by the UID that
>         // created the network. So any attempt to modify a network config that does not belong to us
>         // would result in error.
> ```

Can we also add a note that this means any changes in the passed in config are ignored?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 212 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68#-Kp0pxrzNPq81VLp-YRW:-Kp0pxrzNPq81VLp-YRX:b-vsja4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f1ae9d6daa5f6dd5fa43266f6bd13dbd4de8d74c/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L212)):*
> ```Java
>                     "Connecting to network \""
>                             + existingConfig.SSID
>                             + "\" with its existing configuration");
> ```

Can we log the existing configuration and passed in config even though their formats differ)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 206 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68#-Kp0plg8pRBhHunPVJzg:-Kp1-zk-JPQuMJ-TeIgN:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f1ae9d6daa5f6dd5fa43266f6bd13dbd4de8d74c/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L206)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Can we also add a note that this means any changes in the passed in config are ignored?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 212 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68#-Kp0pxrzNPq81VLp-YRW:-Kp1-O5xbbwjgo1wh9g7:bbyz4nm) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f1ae9d6daa5f6dd5fa43266f6bd13dbd4de8d74c/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L212)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Can we log the existing configuration and passed in config even though their formats differ)?
</blockquote></details>

The only visible fields in the existing config would be SSID, which is the same as the incoming config in this case, so logging it adds no new info.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 212 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68#-Kp0pxrzNPq81VLp-YRW:-Kp1BE56mK0PNJUzglgH:b-phbptl) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f1ae9d6daa5f6dd5fa43266f6bd13dbd4de8d74c/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L212)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

The only visible fields in the existing config would be SSID, which is the same as the incoming config in this case, so logging it adds no new info.
</blockquote></details>

New config is already logged by default.
Logging existing config here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 212 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68#-Kp0pxrzNPq81VLp-YRW:-Kp1BN4MJDCkQUqaWRPC:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f1ae9d6daa5f6dd5fa43266f6bd13dbd4de8d74c/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L212)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

New config is already logged by default.
Logging existing config here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/68#-:-KpK1KVBii1P7YnJmns5:bnfp4nl)*

**Comment by xpconanfan** [comment]
Tested and confirmed that it works:
1. Connect to network1 with Settings
2. Connect to network2 with Settings
3. Connect to network1 with MBS
Device connected to network1 using existing config.

**Pull request merged**
