### PR TITLE
Add Rpcs for enabling/disabling bt snoop log.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/39)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 135 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39#-KiYLACQ0qmgZPftz-4T:-KiYLACQ0qmgZPftz-4U:bnl0b51) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f0294cd10bd761218f599f876715fac3cf7a37c3/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L135)):*
> ```Java
>                     mBluetoothAdapter
>                             .getClass()
>                             .getDeclaredMethod("configHciSnoopLog", boolean.class)
> ```

Do we happen to know when this private API was introduced and if it's ever changed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 135 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39#-KiYLACQ0qmgZPftz-4T:-KiYQ-tjobEXLyoj5KCk:b-5sbqyl) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/f0294cd10bd761218f599f876715fac3cf7a37c3/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L135)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Do we happen to know when this private API was introduced and if it's ever changed?
</blockquote></details>

It was added in KK and never changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 131 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39#-KiYRgtvUtzJPMWezTgI:-KiYRgtvUtzJPMWezTgJ:bkimigv) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/16b53764fbfbda7dd8a0f8d5831956666f498703/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L131)):*
> ```Java
>     }
> 
>     @TargetApi(Build.VERSION_CODES.KITKAT)
> ```

There's an @RpcMinSdk which is actually enforced by the server right?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 132 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39#-KiYRkXXKv0dWSgwBOrJ:-KiYRkXXKv0dWSgwBOrK:bk2dj2y) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/16b53764fbfbda7dd8a0f8d5831956666f498703/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L132)):*
> ```Java
> 
>     @TargetApi(Build.VERSION_CODES.KITKAT)
>     @Rpc(description = "Enable Bluetooth HCI snoop log for debugging.")
> ```

Mind adding a comment for us noobs what the bluetooth HCI log is and how you would retrieve it? Is it printed to logcat? Does it go to some file somewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 131 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39#-KiYRgtvUtzJPMWezTgI:-KiYUm070pYi4FPkIva0:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/16b53764fbfbda7dd8a0f8d5831956666f498703/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L131)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

There's an @RpcMinSdk which is actually enforced by the server right?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 132 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39#-KiYRkXXKv0dWSgwBOrJ:-KiYVra78IarBM0Mf1SM:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/16b53764fbfbda7dd8a0f8d5831956666f498703/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L132)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Mind adding a comment for us noobs what the bluetooth HCI log is and how you would retrieve it? Is it printed to logcat? Does it go to some file somewhere?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/39#-:-KiZSE8CpXSL8yai_A9-:bnfp4nl)*

**Pull request merged**
