### PR TITLE
Fix issues related to WifiManagerSnippet.

### PR DESCRIPTION
**Pull request by adorokhine**
* Version code check was incorrect.
* Missing permission needed to be able to call setWifiApEnabled.
* Lint errors on ApiVersionException, which is what WifiManagerSnippet throws.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/44)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 247 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44#-Kj6Y0y8sr7NuY63xL7r:-Kj6Y0y8sr7NuY63xL7s:bvye1g3) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b905cf458566854125205aac4426feb877ed4463/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L247)):*
> ```Java
> 
>     private void verifyApiVersionForSoftAp() throws ApiVersionException {
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
> ```

This should be strictly '>'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 270 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44#-Kj6cUiYS7smtlIlHLbc:-Kj6cUiZbyD_hD68POw5:b-3zpt55) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b905cf458566854125205aac4426feb877ed4463/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L270)):*
> ```Java
>      * Enable Wi-Fi Soft AP (hotspot).
>      *
>      * <p>Does not work for release N.
> ```

Need to update the javadocs too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44)*

**Comment by adorokhine** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 247 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44#-Kj6Y0y8sr7NuY63xL7r:-KjA9Hq-PcsbnspD0ieO:b-jvnbib) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b905cf458566854125205aac4426feb877ed4463/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L247)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This should be strictly '>'
</blockquote></details>

Removed completely. As discussed, we've been able to run this on SDK25 so leaving the version check out until we can reproduce some incompatibility.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 270 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44#-Kj6cUiYS7smtlIlHLbc:-KjA9HSmVFv9nnvupxPg:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b905cf458566854125205aac4426feb877ed4463/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L270)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Need to update the javadocs too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/44#-:-KjAzUn7PFoLPoL42gx7:bnfp4nl)*

**Pull request merged**
