### PR TITLE
Add SMS snippet

### PR DESCRIPTION
**Pull request by arammelk**
Adding simple sms snippet.

Use examples:
callback = dut.mbs.asyncWaitForSms()
message = callback.waitAndGet('ReceivedSms', 300).data['message']

dut.mbs.sendSms('+16501234567', 'hello snippet')

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/69)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java, line 31 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxK2zzNlX5fIpHE9Hr:-KoxK2zzNlX5fIpHE9Hs:bprizfj) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java#L31)):*
> ```Java
> import com.google.android.mobly.snippet.event.SnippetEvent;
> 
> public class IncomingSmsBroadcastReceiver extends BroadcastReceiver {
> ```

if this is only used by  `SmsSnippet`, can it be an inner private static class?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java, line 66 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxJvNHwteA3twE4K1Z:-KoxJvNHwteA3twE4K1_:bs3ousn) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java#L66)):*
> ```Java
>         }
>     }
> }
> ```

missing an extra line at the end.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 31 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKd_y-IcDVVixJngk:-KoxKd_z49b47mZiztBg:b-zcswlm) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L31)):*
> ```Java
> public class SmsSnippet implements Snippet {
> 
>     private static final int MAX_TEXT_MESSAGE_SIZE = 160;
> ```

should this name reflect this is the size limit for a single message?
it seems that one can still send a longer message longer than this via the Rpcs.

Also would be nice to include the unit

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KoxKvtRFg09Olaivohc:b-qyo2eg) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
> ```Java
> 
>     @Rpc(description = "Sends SMS message to a specified phone number.")
>     public void sendSms(String phoneNumber, String message) throws InterruptedException {
> ```

Is there no signal to wait for to confirm message was sent?
for non-async `Rpc`, we usually make it so that when the method returns, the operation is complete.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 51 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKTrE99llkexekPW_:-KoxKTrE99llkexekPWa:bu2qexo) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L51)):*
> ```Java
>     }
> 
>     @AsyncRpc(description = "Wait for incoming SMS message.")
> ```

need to reflect "async" in description

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 58 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKEg_uQDSJsYpJ8_Y:-KoxKEg_uQDSJsYpJ8_Z:b-iy36bu) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L58)):*
> ```Java
> 
>     @Override
>     public void shutdown() {}
> ```

If snippet exists before the message is received, do we need to unregister the receiver to release system resource, or does it not matter?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 59 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKBI0h2QtXjPH8xHr:-KoxKBI0h2QtXjPH8xHs:b-oh09a) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L59)):*
> ```Java
>     @Override
>     public void shutdown() {}
> }
> ```

missing extra line at the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 31 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKd_y-IcDVVixJngk:-Kp4K5r_wJoVLiLVhxa-:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L31)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should this name reflect this is the size limit for a single message?
it seems that one can still send a longer message longer than this via the Rpcs.

Also would be nice to include the unit
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-Kp4K70ErfjzPc4qmyhX:bybwt59) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Is there no signal to wait for to confirm message was sent?
for non-async `Rpc`, we usually make it so that when the method returns, the operation is complete.
</blockquote></details>

There is, can pass in PendingIntent/List of PendingIntent objects to the 2 send methods. Added OutboundSmsReceiver to handle posting the event once sent action is complete. Changed sendSms to AsyncRpc from RPC.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 51 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKTrE99llkexekPW_:-Kp4KUqphqWA3D43QiWZ:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L51)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

need to reflect "async" in description
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 58 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKEg_uQDSJsYpJ8_Y:-Kp4KYFIKzL7YQpP0KYT:bydg0rl) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L58)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

If snippet exists before the message is received, do we need to unregister the receiver to release system resource, or does it not matter?
</blockquote></details>

They don't seem to stay alive. Tested this by killing mbs after starting asyncWaitForSms and with the new asyncSendSms, BroadcastReceiver is killed then as well. There are instances where you can keep a BroadcastReceiver alive in a service or app in background, but that doesn't apply here.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 59 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKBI0h2QtXjPH8xHr:-Kp4KVZ9ukLPDwk2M9OE:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L59)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

missing extra line at the end.
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java, line 31 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxK2zzNlX5fIpHE9Hr:-Kp4JgiuOkvJPL-tnXOK:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java#L31)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

if this is only used by  `SmsSnippet`, can it be an inner private static class?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java, line 66 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxJvNHwteA3twE4K1Z:-Kp4Qll3tBn4ozK6_GNr:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/IncomingSmsBroadcastReceiver.java#L66)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

missing an extra line at the end.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KpHdwbbmjGtR5vnvAbe:b-25u88z) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

There is, can pass in PendingIntent/List of PendingIntent objects to the 2 send methods. Added OutboundSmsReceiver to handle posting the event once sent action is complete. Changed sendSms to AsyncRpc from RPC.
</blockquote></details>

So it is also ok to add `sendSms` and make sure it does not return until the msg is sent, whichever is easier to use for the tests.
(Seems like the synchronized version might be easier? Your call)

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 118 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHf-Zu_-v0HmbZBwy7:-KpHf-Zu_-v0HmbZBwy8:b-123wtq) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L118)):*
> ```Java
> 
>                         if (mExpectedMessageCount > 0 ) {
>                             mExpectedMessageCount--;
> ```

So multiple events need to be waited and confirmed before we are sure the whole message is sent?
This seems a bit complicated.

Maybe we can make the send Rpc synchronous?
Or add a javadoc for the send Rpc with sample usage including the event waiting part?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 158 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHl_JlGmVG8RuTIals:-KpHl_JlGmVG8RuTIalt:b-7pr6j2) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L158)):*
> ```Java
> 
>                     SmsMessage sms = msgs[0];
>                     String sender = sms.getOriginatingAddress();
> ```

are we sure all the messages will have the same originating address?
what if two different devices sent messages to the same device at the same time, would we get messages from both senders here?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 159 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHl6IkGOdCy9lOYrL8:-KpHl6IkGOdCy9lOYrL9:b-713oit) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L159)):*
> ```Java
>                     SmsMessage sms = msgs[0];
>                     String sender = sms.getOriginatingAddress();
>                     event.getData().putString("sender", sender);
> ```

We generally try to follow the field names of the Java object the event maps to, like "OriginatingAddress" and "MessageBody".
Any other fields that might be useful?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KpHpLSI4tO4arX_bCpp:b-ji7rb2) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

So it is also ok to add `sendSms` and make sure it does not return until the msg is sent, whichever is easier to use for the tests.
(Seems like the synchronized version might be easier? Your call)
</blockquote></details>

Would need to wait for the OutboundSmsReceiver's onReceive to be triggered.  Is there a recommended method for waiting for a BroadcastReceiver's onReceive method to be triggered? The best I can think of is a variable in SmsSnippet that tracks if it is actively waiting for message sent confirmation, but seems like it could be cleaner?  Open to suggestions to make this a sync call.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 118 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHf-Zu_-v0HmbZBwy7:-KpHpvezY_vjU9yxp9d9:b-q0e470) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L118)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

So multiple events need to be waited and confirmed before we are sure the whole message is sent?
This seems a bit complicated.

Maybe we can make the send Rpc synchronous?
Or add a javadoc for the send Rpc with sample usage including the event waiting part?
</blockquote></details>

Multiple events only in the case of  a multi-part SMS that went over the 160 character limit.  See comment above about making it synchronous.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 158 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHl_JlGmVG8RuTIals:-KpHrpC0MicgcKdMoc_b:bqwqtc2) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L158)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

are we sure all the messages will have the same originating address?
what if two different devices sent messages to the same device at the same time, would we get messages from both senders here?
</blockquote></details>

From documentation and how it seems to work, multiple messages here are multiple PDUs from the same multi-part SMS. So the originating address should be the same.

The scenario you mention would trigger two separate  of onReceive calls for SmsReceiver (per recipient).

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 159 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHl6IkGOdCy9lOYrL8:-KpHuB5lRnz8I73XKKPB:b-5jkxko) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L159)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

We generally try to follow the field names of the Java object the event maps to, like "OriginatingAddress" and "MessageBody".
Any other fields that might be useful?
</blockquote></details>

Done. Not sure if anyone would care about the other fields, can grab the raw PDU maybe? https://developer.android.com/reference/android/telephony/gsm/SmsMessage.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KpIMEkUVcpd65-gyoGQ:b84pa1a) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

Would need to wait for the OutboundSmsReceiver's onReceive to be triggered.  Is there a recommended method for waiting for a BroadcastReceiver's onReceive method to be triggered? The best I can think of is a variable in SmsSnippet that tracks if it is actively waiting for message sent confirmation, but seems like it could be cleaner?  Open to suggestions to make this a sync call.
</blockquote></details>

We could do an active loop wait, or we could do a [synchronized wait with wait/notify](https://docs.oracle.com/javase/tutorial/essential/concurrency/guardmeth.html)?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 159 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHl6IkGOdCy9lOYrL8:-KpIJ6vRpwaBkLIZ2vXV:b-4vau1x) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L159)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

Done. Not sure if anyone would care about the other fields, can grab the raw PDU maybe? https://developer.android.com/reference/android/telephony/gsm/SmsMessage.html
</blockquote></details>

Could the timestamp be useful for some tests?
I don't know how the timestamp is supposed to be calculated if multiple messages were received though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KpJXrq6aD8ShW_RrlTQ:b-v0rigz) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
Done. Mobly seems to already do a lot of this, switched to using its EventCache/SnippetEvents instead. Now sendSms is synchronous. Example run through snippet shell:

>>> result = s.sendSms("12345", "Hello world")
>>> import pprint
>>> pprint.pprint(result)
{u'sent': True}
>>>

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 159 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpHl6IkGOdCy9lOYrL8:-KpJfA1X2b-oncWLSiyY:bto508t) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5d572483e05b665b38fa0ee834a7faf37c1bd0f4/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L159)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Could the timestamp be useful for some tests?
I don't know how the timestamp is supposed to be calculated if multiple messages were received though.
</blockquote></details>

Not sure, can be added later if it is needed. I imagine the timestamp of each individual PDU isn't that important to most.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KpJfr5iBshTP1AiYJbn:b-tiv2mc) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

Done. Mobly seems to already do a lot of this, switched to using its EventCache/SnippetEvents instead. Now sendSms is synchronous. Example run through snippet shell:

>>> result = s.sendSms("12345", "Hello world")
>>> import pprint
>>> pprint.pprint(result)
{u'sent': True}
>>>

</blockquote></details>

Meant to add this here and not in the commit messages. 

This shares code with EventSnippet in Mobly Snippet Lib. I'm not sure what the accepted practice is for sharing code across github projects. Should I refactor some of the event code in Mobly Bundle Lib into EventUtils, then use that in Mobly Bundled Snippets to avoid duplicating this?

I still want to check this is in as is, to have a working version earlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 113 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpLF-vMDJ0MJdkf3LGX:-KpLF-vN4G2xBxi-AGEk:b-eh4qvv) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1e6e5c1643373be11beb08e435141a45a0127b91/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L113)):*
> ```Java
>     }
> 
>     @TargetApi(Build.VERSION_CODES.KITKAT)
> ```

Out of curiosity, what needs this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KpLI1qMwg-PTO-lqPlY:b9sm0kr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

Meant to add this here and not in the commit messages. 

This shares code with EventSnippet in Mobly Snippet Lib. I'm not sure what the accepted practice is for sharing code across github projects. Should I refactor some of the event code in Mobly Bundle Lib into EventUtils, then use that in Mobly Bundled Snippets to avoid duplicating this?

I still want to check this is in as is, to have a working version earlier.
</blockquote></details>

That's an interesting way of using events! :+1: 
Did not think of that when we added the event mechanism.

We should probably refactor other places in MBS if there's a similar use case.
I don't remember other synchronous rpc waiting for broadcast though.

One more thing though.
In MBS, usually the sync rpc would through an exception if the operation failed.
So maybe we should do the same here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 42 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KoxKvtRFg09Olaivohb:-KpTQxxEZ5MkLKvnAMlu:bb6un1j) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/67a4071d4b6dab52a7edcc6677d7545c107c0594/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L42)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

That's an interesting way of using events! :+1: 
Did not think of that when we added the event mechanism.

We should probably refactor other places in MBS if there's a similar use case.
I don't remember other synchronous rpc waiting for broadcast though.

One more thing though.
In MBS, usually the sync rpc would through an exception if the operation failed.
So maybe we should do the same here?
</blockquote></details>

Done

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 113 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpLF-vMDJ0MJdkf3LGX:-KpTQnS6tum_88CjVxB1:bhgcx62) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1e6e5c1643373be11beb08e435141a45a0127b91/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L113)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Out of curiosity, what needs this?
</blockquote></details>

According to AS it is because of -> Intents.SMS_RECEIVED_ACTION

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 77 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpaBf-nx_yKjU1Gyj2z:-KpaBf-nx_yKjU1Gyj3-:b3tndas) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1b2c5ec7ec3233293291d6dc0ce09770bac5bc51/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L77)):*
> ```Java
>     /**
>      * Send SMS and wait for confirmation before returning.
>      *
> ```

let's add some info on the timeout here.
like how long we wait before we time out and declare msg sending fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 77 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-KpaBf-nx_yKjU1Gyj2z:-KpbdVQgniENzinW7pGf:b-ffq3iz) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1b2c5ec7ec3233293291d6dc0ce09770bac5bc51/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L77)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

let's add some info on the timeout here.
like how long we wait before we time out and declare msg sending fail.
</blockquote></details>

oops! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69)*

**Comment by arammelk** [comment]
Ping

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/69#-:-KprIjMi3jd08u8DNpxU:bnfp4nl)*

**Pull request merged**
