### PR TITLE
Add sync waitForSms

### PR DESCRIPTION
**Pull request by arammelk**
Add sync version of waitForSms

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/76)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 66 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsFUH_k52nf6rLLT3d0:-KsFUH_k52nf6rLLT3d1:b-uu5jqr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73c9544412291619edbdd44bdc4aedf5e9ec6730/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L66)):*
> ```Java
>     }
> 
>     public static SnippetEvent waitForSnippetEvent(
> ```

Need javadoc detailing the intended usage of this method.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 68 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsFUqGRCvWOtV9JauxA:-KsFUqGRCvWOtV9JauxB:b-144y0j) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73c9544412291619edbdd44bdc4aedf5e9ec6730/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L68)):*
> ```Java
>     public static SnippetEvent waitForSnippetEvent(
>             String callbackId, String eventName, @Nullable Integer timeout)
>             throws InterruptedException {
> ```

How about catch the `InterruptedException` and throw `e.getCause()` this way we don't need to catch it and throw a custom error with a hard coded message on the caller side. We could just let the actual exception through

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 66 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsFUH_k52nf6rLLT3d0:-KsFsMJ3zjI7xPhuoTqP:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73c9544412291619edbdd44bdc4aedf5e9ec6730/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L66)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Need javadoc detailing the intended usage of this method.
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 68 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsFUqGRCvWOtV9JauxA:-KsFsMyTZ8suv3ekG5J8:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73c9544412291619edbdd44bdc4aedf5e9ec6730/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L68)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

How about catch the `InterruptedException` and throw `e.getCause()` this way we don't need to catch it and throw a custom error with a hard coded message on the caller side. We could just let the actual exception through
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 83 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGCG4tioAnNdnRZP-p:-KsGCG4tioAnNdnRZP-q:betw3y9) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/3c615a63e67ffbe621c432939fcb5d5a9f090945/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L83)):*
> ```Java
>             String callbackId, String eventName, @Nullable Integer timeout) throws Throwable {
>         if (timeout == null) {
>             timeout = DEFAULT_TIMEOUT_MILLISECOND;
> ```

let's not have an arbitrary default timeout value here, which could be confusing.

I see two alternatives:
1. If no timeout is provided, use the `pollFirst` without timeout param
2. Simply remove the default value behavior and force caller to provide a timeout value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 83 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGCG4tioAnNdnRZP-p:-KsGGr65SJiwFgQXD0CU:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/3c615a63e67ffbe621c432939fcb5d5a9f090945/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L83)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

let's not have an arbitrary default timeout value here, which could be confusing.

I see two alternatives:
1. If no timeout is provided, use the `pollFirst` without timeout param
2. Simply remove the default value behavior and force caller to provide a timeout value.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 74 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGIUFi4LXjV3VFGd2A:-KsGIUFjpwT0ksFx2iut:b-2kjawp) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/508033a50bff64af42b3cb9f339f7e3b3ecb54a7/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L74)):*
> ```Java
>      * @param callbackId String callbackId that we want to wait on.
>      * @param eventName String event name that we are waiting on.
>      * @param timeout int if not null will use this as the timeout for waiting for the event.
> ```

specify the behavior of when timeout is null.
specify the time unit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 74 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGIUFi4LXjV3VFGd2A:-KsHOz5gGyQl5WMTB_VK:b2w03em) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/508033a50bff64af42b3cb9f339f7e3b3ecb54a7/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L74)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

specify the behavior of when timeout is null.
specify the time unit.
</blockquote></details>

not having a timeout will not work,  pollFirst will just return null if there is nothing in the list. timeouts are back and not nullable anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 88 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsHRqFy9jCjjkdI2zD4:-KsHRqFzbQJhCQWx_COM:b9vd5bc) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/16aad4f701d9223432e9b690e928f21d80de714a/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L88)):*
> ```Java
>             throw e.getCause();
>         }
>         return result;
> ```

should we throw here if `result` is null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 74 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGIUFi4LXjV3VFGd2A:-KsHRJSFLO1GltwtV944:b-bzmh0k) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/508033a50bff64af42b3cb9f339f7e3b3ecb54a7/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L74)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

not having a timeout will not work,  pollFirst will just return null if there is nothing in the list. timeouts are back and not nullable anymore.
</blockquote></details>

Oh forgot to mention, if you're concerned about arbitrary default timeouts. You should take a look at Mobly Snippet Lib

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 88 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsHRqFy9jCjjkdI2zD4:-KsHZ3n-J_dAiKszcW9c:bg3d62y) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/16aad4f701d9223432e9b690e928f21d80de714a/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L88)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should we throw here if `result` is null?
</blockquote></details>

I think that makes more sense, the clients of this wont have to worry about checking for null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 74 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGIUFi4LXjV3VFGd2A:-KsHczF9kbwWfLEdG-g2:b91kr9z) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/508033a50bff64af42b3cb9f339f7e3b3ecb54a7/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L74)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

Oh forgot to mention, if you're concerned about arbitrary default timeouts. You should take a look at Mobly Snippet Lib
</blockquote></details>

Err failed to link to file + line: https://github.com/google/mobly-snippet-lib/blob/master/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/event/EventSnippet.java

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 74 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGIUFi4LXjV3VFGd2A:-KsHemb68RadLWND8TsA:buxl5ld) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/508033a50bff64af42b3cb9f339f7e3b3ecb54a7/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L74)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

Err failed to link to file + line: https://github.com/google/mobly-snippet-lib/blob/master/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/event/EventSnippet.java
</blockquote></details>

Ya, I only realized the pain after using those T_T

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 96 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsHerTTxPn2RfA9FJn_:-KsHerTTxPn2RfA9FJna:bu617y) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/fa893d77444c4a9dbef7cc18ff03f52c01be918e/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L96)):*
> ```Java
> 
>         if (result == null) {
>             throw new UtilsException("Timed out waitinng for SnippetEvent: " + callbackId);
> ```

let's include how long the timeout was in the message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 74 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsGIUFi4LXjV3VFGd2A:-KsHgY3W7ulSsWFuqf4W:b32vhv) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/508033a50bff64af42b3cb9f339f7e3b3ecb54a7/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L74)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Ya, I only realized the pain after using those T_T
</blockquote></details>

:(

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 96 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsHerTTxPn2RfA9FJn_:-KsHgVsGiYsbwBKCSDza:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/fa893d77444c4a9dbef7cc18ff03f52c01be918e/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L96)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

let's include how long the timeout was in the message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 97 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsHkSwgMNzbxnowqSnS:-KsHkSwgMNzbxnowqSnT:b-ffihk0) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/fef3442507485873579f03053727465492372e26/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L97)):*
> ```Java
> 
>         if (result == null) {
>             throw new UtilsException(
> ```

should we throw Java's `TimeoutException` instead?

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeoutException.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by arammelk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 97 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-KsHkSwgMNzbxnowqSnS:-KsICCkbJ8mKLApwkSCy:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/fef3442507485873579f03053727465492372e26/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L97)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should we throw Java's `TimeoutException` instead?

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/TimeoutException.html
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/76#-:-KsKh3_Jh2V9qw-btNJT:bnfp4nl)*

**Pull request merged**
