### PR TITLE
Add method to clear configured networks

### PR DESCRIPTION
**Pull request by dthkao**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/55)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAoQTDuBnMvs9ZfTyQ:-KmAoQTDuBnMvs9ZfTyR:b-2cavjx) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/bd395ddae6ab0c222f6c8eb0444b83addb10827b/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
> ```Java
>         Log.d("Clearing all configured networks.");
>         for (WifiConfiguration config : mWifiManager.getConfiguredNetworks()) {
>             wifiRemoveNetwork(config.networkId);
> ```

I think we should still try to clear the other networks if one fails to be removed.
We can log the ones that failed to be removed, or add their names in the final exception.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAt-YbspSM_pu-tZ0n:-KmAt-YbspSM_pu-tZ0o:b-31ixau) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/194f94f4182b9237bdb349202550558398833b39/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
> ```Java
>     public void wifiClearConfiguredNetworks() throws WifiManagerSnippetException {
>         Log.d("Clearing all configured networks.");
> 	List<String> unremovedSsids = new ArrayList();
> ```

tabs?
did you run linter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAoQTDuBnMvs9ZfTyQ:-KmAtH47pYvnCVQQ5Mf4:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/bd395ddae6ab0c222f6c8eb0444b83addb10827b/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I think we should still try to clear the other networks if one fails to be removed.
We can log the ones that failed to be removed, or add their names in the final exception.
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAt-YbspSM_pu-tZ0n:-KmAtAYFdZ0O6ez7Wfkv:bo41hcm) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/194f94f4182b9237bdb349202550558398833b39/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

tabs?
did you run linter?
</blockquote></details>

working in vi on an unfamiliar laptop. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAt8U3VuQFg3pqvPDJ:-KmAt8U3VuQFg3pqvPDK:be1zrhr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/194f94f4182b9237bdb349202550558398833b39/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
> ```Java
>     public void wifiClearConfiguredNetworks() throws WifiManagerSnippetException {
>         Log.d("Clearing all configured networks.");
> 	List<String> unremovedSsids = new ArrayList();
> ```

`failedConfigs` since we are removing configs not just ssids here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAt8U3VuQFg3pqvPDJ:-KmAtblhfBVNpYrOzZot:bjxe1p7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/194f94f4182b9237bdb349202550558398833b39/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`failedConfigs` since we are removing configs not just ssids here?
</blockquote></details>

Is that information useful in the exception message? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAt8U3VuQFg3pqvPDJ:-KmAtWkaibFsbzKQgYJw:ban59e1) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/194f94f4182b9237bdb349202550558398833b39/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Is that information useful in the exception message? 
</blockquote></details>

Also we should probably log the whole config, not just the ssid.
e.g. it would be good to know the networkId and other info, which could be helpful in figuring out why it failed to be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 65 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAt8U3VuQFg3pqvPDJ:-KmAueRm2pCFtFrQf08X:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/194f94f4182b9237bdb349202550558398833b39/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L65)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Also we should probably log the whole config, not just the ssid.
e.g. it would be good to know the networkId and other info, which could be helpful in figuring out why it failed to be removed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 64 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAuxKKTpuelw42IL3I:-KmAuxKLbtUqUZbkXQfi:bxlkbl5) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a4beefbc87e5e1be225f04cd1a5adb437247b951/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L64)):*
> ```Java
>     @Rpc(description = "Clears all configured networks.")
>     public void wifiClearConfiguredNetworks() throws WifiManagerSnippetException {
>         Log.d("Clearing all configured networks.");
> ```

this log msg doesn't seem to add much, considering all the rpc calls are already logged?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 64 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmAuxKKTpuelw42IL3I:-KmAygDyqccvcqA4Y597:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a4beefbc87e5e1be225f04cd1a5adb437247b951/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L64)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this log msg doesn't seem to add much, considering all the rpc calls are already logged?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-:-KmE2Najv4I8FGhfR6cQ:bnfp4nl)*

**Comment by adorokhine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 64 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmE58LiqV0XnqphX1i4:-KmE58LiqV0XnqphX1i5:b9ai0ze) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/383ecfa68aa721c808c5ec3a80540db93648b6a6/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L64)):*
> ```Java
>     @Rpc(description = "Clears all configured networks.")
>     public void wifiClearConfiguredNetworks() throws WifiManagerSnippetException {
>         List<WifiConfiguration> unremovedConfigs = new ArrayList();
> ```

Does this compile without warnings? (Missing diamond operator).
If not, can we modify our build scripts to make warnings like this fatal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 64 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmE58LiqV0XnqphX1i4:-KmKZJ3UtmlUfFsKGn-u:burgves) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/383ecfa68aa721c808c5ec3a80540db93648b6a6/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L64)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Does this compile without warnings? (Missing diamond operator).
If not, can we modify our build scripts to make warnings like this fatal?
</blockquote></details>

Fixed here. It does warn already, I just missed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 64 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmE58LiqV0XnqphX1i4:-KmV5W09qMXKsxgp24Ln:b-c8g6sk) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/383ecfa68aa721c808c5ec3a80540db93648b6a6/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L64)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Fixed here. It does warn already, I just missed it.
</blockquote></details>

Any way we can make warnings like these fatal during compilation? Does java have a -Werror equivalent? (not for this PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-:-KmV5lq6xu1aVz4JISCP:bnfp4nl)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 64 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmE58LiqV0XnqphX1i4:-KmVIa899wH_eROw8hpQ:b-6s6a5t) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/383ecfa68aa721c808c5ec3a80540db93648b6a6/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L64)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Any way we can make warnings like these fatal during compilation? Does java have a -Werror equivalent? (not for this PR)
</blockquote></details>

https://github.com/google/mobly-bundled-snippets/pull/58?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by dthkao** [comment]
PTAL

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-:-KmXkEnR-Ol0XJdoVtuG:bb71pro)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 77 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmY2d4a9mUgk4baZzbN:-KmY2d4a9mUgk4baZzbO:b-yk7zde) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/effa9491d7b0ac60acc718ba2b8204fc2776654d/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L77)):*
> ```Java
>         }
>         if (!failedConfigs.isEmpty()) {
>             throw new WifiManagerSnippetException("Failed to remove networks: " + unremovedConfigs);
> ```

shouldn't the log line use `failedConfigs` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 77 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-KmY2d4a9mUgk4baZzbN:-KmY4lvsrVLwNSDYpPFq:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/effa9491d7b0ac60acc718ba2b8204fc2776654d/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L77)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

shouldn't the log line use `failedConfigs` instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/55#-:-KmY54At8gF6TxJQg0k0:bnfp4nl)*

**Pull request merged**
