### PR TITLE
Fix version warnings for gradle builds

### PR DESCRIPTION
**Pull request by kdart**
Make everything the current recommended version. 

build and presubmit phase passes.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/87)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Still failing with #83:

```
$ ./gradlew presubmit
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.495 secs
```

**Comment by kdart** [comment]
Hopefully this last round of updating and fixing stuff will work and last for some time more. 

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-:-Kvdl7OZvBbgB7mlUKxm:b-sypi2v)*

**Comment by xpconanfan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 4 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvdlH1LAz5QiEKtKsnG:-KvdlH1LAz5QiEKtKsnH:b-pwrj6c) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c0448307153eb5b4f42ba435bd517064e6989f4b/build.gradle#L4)):*
> ```Gradle
>     repositories {
>         jcenter()
>         google()
> ```

where did this come from?
it's causing errors in Android Studio.
Please use public android studio when developing for github.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 4 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvdlH1LAz5QiEKtKsnG:-KvdlU1jYuKEhzDUFzRH:b-bttq56) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c0448307153eb5b4f42ba435bd517064e6989f4b/build.gradle#L4)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

where did this come from?
it's causing errors in Android Studio.
Please use public android studio when developing for github.
</blockquote></details>

Studio added it, it seems it's needed to get some of the latest studio plugins. I don't think it will cause problems in stable versions. Did it cause a problem for you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by xpconanfan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 4 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvdlH1LAz5QiEKtKsnG:-KvdmGlySeaRHqbIF4GI:bg7u1ox) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c0448307153eb5b4f42ba435bd517064e6989f4b/build.gradle#L4)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

Studio added it, it seems it's needed to get some of the latest studio plugins. I don't think it will cause problems in stable versions. Did it cause a problem for you?
</blockquote></details>

It does not compile at all.

Make sure you are using public android studio without google infra?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 4 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvdlH1LAz5QiEKtKsnG:-KvdmYHGk5USNaJP51Ss:b-5kixdx) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c0448307153eb5b4f42ba435bd517064e6989f4b/build.gradle#L4)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It does not compile at all.

Make sure you are using public android studio without google infra?
</blockquote></details>

OK, I'll try with public parts later. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 4 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvdlH1LAz5QiEKtKsnG:-KveBXzUK8p7UNpHLDC0:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c0448307153eb5b4f42ba435bd517064e6989f4b/build.gradle#L4)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

OK, I'll try with public parts later. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by xpconanfan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[build.gradle, line 7 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KveMi7Qhay_lZNRd4OJ:-KveMi7Qhay_lZNRd4OK:b-a6e9en) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/2797e51535fd0906326ba8785159d6d2f96f1e7d/build.gradle#L7)):*
> ```Gradle
>     dependencies {
>         classpath 'com.android.tools.build:gradle:2.3.3'
>         classpath 'me.tatarka:gradle-retrolambda:3.5.0'
> ```

why removing this? we didn't have problem with this before.

---

*[build.gradle, line 37 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KveMmAyITzk37wVjOX8:-KveMmAyITzk37wVjOX9:b-h1mdky) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/3899e886f84603c9e30fff3ed339961c79698c52/build.gradle#L37)):*
> ```Gradle
>     defaultConfig {
>         applicationId "com.google.android.mobly.snippet.bundled"
>         minSdkVersion 15
> ```

why do we have to increase this? we want to keep it as low as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by xpconanfan** [comment]
Multiple errors in example 1, 2 and 3 when syncing gradle

**Comment by kdart** [comment]
What examples? I don't see any on the source tree. What errors are they? On my system, the following all work.

> ./gradlew assembleDebug
> ./gradlew test
> ./gradlew lint
> ./gradlew presubmit

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[build.gradle, line 7 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KveMi7Qhay_lZNRd4OJ:-KveY37liLBSni0PGlEn:b-eyv2ph) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/2797e51535fd0906326ba8785159d6d2f96f1e7d/build.gradle#L7)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why removing this? we didn't have problem with this before.
</blockquote></details>

Removing which? this was causing some of those compatibility problems.

---

*[build.gradle, line 37 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KveMmAyITzk37wVjOX8:-KveYAt1ZbwwL_MyGLVS:b-1sdfcx) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/3899e886f84603c9e30fff3ed339961c79698c52/build.gradle#L37)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why do we have to increase this? we want to keep it as low as possible.
</blockquote></details>

Previous IDE import suggested it was too low, and could be increased without losing devices. Since guava is tested with API 15 and 15 didn't get a complaint I made it 15.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-:-KveXgihcixW6mUotXqh:bqr8jfz)*

**Comment by xpconanfan** [comment]
Sorry, i used the wrong repo.

After `presubmit`, instead of opening the page, the source code of the html page got printed in my console (Mac).... This doesn't seem right...

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 7 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KveMi7Qhay_lZNRd4OJ:-KvebC4QpGf8VObAT-V-:b-n01g4k) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/2797e51535fd0906326ba8785159d6d2f96f1e7d/build.gradle#L7)):*
>  classpath 'me.tatarka:gradle-retrolambda:3.5.0'
I see this being removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-:-KvebU6Z6d6jL83xYTcv:ba2ri7h)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 7 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KveMi7Qhay_lZNRd4OJ:-KveySCYz5pGPbA1ClZX:b-38a4vp) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/2797e51535fd0906326ba8785159d6d2f96f1e7d/build.gradle#L7)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

>  classpath 'me.tatarka:gradle-retrolambda:3.5.0'
I see this being removed
</blockquote></details>

Oh, learned that wasn't needed if using latest SDK with java 8. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
OK, finally got to try it on my iMac and figure out what it reports. Now it works, at least if you have Chrome set as your default browser.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-:-Kvf2Gbp0aKg2gvKAktV:bo3auti)*

**Comment by xpconanfan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-KvfDb5B5qAT5BU91Xfz:b-n96ie6) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
> ```Gradle
>     }
>     lintOptions {
>         abortOnError false
> ```

We should leave this as `true` so ppl don't skip errors?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-KvhCbfy1MiW_t3O8dVg:b-iglxh7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

We should leave this as `true` so ppl don't skip errors?
</blockquote></details>

This means it will (I hope) continue on error and then pop up the report in the browser exactly so people don't skip errors. The browser report is nicer to read.  This makes the presubmit target work even with lint errors. Otherwise gradle aborts and the report is not displayed by the subsequent rule. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-KvhF8lzhhUE-NBoWc3f:b-90djc3) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

This means it will (I hope) continue on error and then pop up the report in the browser exactly so people don't skip errors. The browser report is nicer to read.  This makes the presubmit target work even with lint errors. Otherwise gradle aborts and the report is not displayed by the subsequent rule. 
</blockquote></details>

Try temporarily commenting out the `disable` line there to see how it would work.  I'm kind of 50-50 on it, but the report is more informative than a build abort, and the presubmit more convenient that copying the path from the terminal and opening it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by xpconanfan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-KvhL4YynLatkfUFuqZB:b-ej1u8) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

Try temporarily commenting out the `disable` line there to see how it would work.  I'm kind of 50-50 on it, but the report is more informative than a build abort, and the presubmit more convenient that copying the path from the terminal and opening it. 
</blockquote></details>

This only aborts on error right?
The html is nice but it's also easy for people to simply not read it, whereas a build abort is hard to ignore per habits?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-KvhMiRBP3uuwNZSps7U:bhvv2no) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This only aborts on error right?
The html is nice but it's also easy for people to simply not read it, whereas a build abort is hard to ignore per habits?
</blockquote></details>

It causes, as far as I can tell, the lint tool to not report a non-zero exit status to gradle, so that gradle will continue. But lint will still report all the errors it found. 
Not that easy to ignore, since it should also focus the browser. But if it fails on error that browser activation won't happen. The report has some useful hints and background information in it that also makes it easier to fix the problem.   

It also kind of bugs me that it reports BUILD FAILURE when it actually does build, it just may have a some small style issue that could be ignored during iterative change-build-debug cycle. It before a PR request (presubmit) does it need to finally be addressed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by xpconanfan** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-Kvhi1VQxmb2RoAQD6XA:b-l78v8n) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

It causes, as far as I can tell, the lint tool to not report a non-zero exit status to gradle, so that gradle will continue. But lint will still report all the errors it found. 
Not that easy to ignore, since it should also focus the browser. But if it fails on error that browser activation won't happen. The report has some useful hints and background information in it that also makes it easier to fix the problem.   

It also kind of bugs me that it reports BUILD FAILURE when it actually does build, it just may have a some small style issue that could be ignored during iterative change-build-debug cycle. It before a PR request (presubmit) does it need to finally be addressed.

</blockquote></details>

Ok, if we want to change the process, let's emphasize in README that one needs to address *all* errors and warnings from the lint report before uploading for review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-KvhlrPq2PNhibc3JhVS:bgwf4sw) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Ok, if we want to change the process, let's emphasize in README that one needs to address *all* errors and warnings from the lint report before uploading for review
</blockquote></details>

Sure, I'll update the doc. However, it seems to me that lint was never run before so this is not exactly changing the process. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by kdart** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.gradle, line 52 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-KvfDb5B5qAT5BU91Xfy:-Kvhn6nobb8mA8KptBuo:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/db64d97c8303f9bca12b2a27ee06ea01d60fe40c/build.gradle#L52)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

Sure, I'll update the doc. However, it seems to me that lint was never run before so this is not exactly changing the process. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/87#-:-KvhwxSiZ4smGJCc7U_w:bnfp4nl)*

**Pull request merged**
