### PR TITLE
Minor bug fix to btUnpairedDevice()

### PR DESCRIPTION
**Pull request by lrbom**
Success case should not throw exception

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/61)

### CODE REVIEW

**Comment by adorokhine** [comment]
:lgtm:
Waiting for final approval from Ang or David.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/61#-:-KmZGMQm3YD1EeEeFPb2:b-gkr2ol)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/61#-:-KmZdXWLZOvoc3tq1yOT:bnfp4nl)*

**Comment by xpconanfan** [comment]
@lrbom You may want to create a new branch from master's head the next time :)

**Comment by lrbom** [comment]
Yes, will do! Sorry for having the old commits there.

**Pull request merged**
