### PR TITLE
Add Bluetooth Rpcs needed to support making the device discoverable.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/41)

### CODE REVIEW

**Comment by adorokhine** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 108 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj5zLeer3-_EQBVIXAY:-Kj5zLefGlaSam1tLHAO:b-ndvvbb) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L108)):*
> ```Java
>                         + "serialized BluetoothDevice objects."
>     )
>     public JSONArray btDiscoverAndGetResults()
> ```

When I executed this method, it only returned one element and then threw up a bluetooth pairing request which interrupted the UI. When I ran it again it seemingly succeeded. Do you see the same thing when you run it?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 151 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj6-BnaTO0vcN7kRlft:-Kj6-BnaTO0vcN7kRlfu:b2b6rpn) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L151)):*
> ```Java
>         }
>         if (!success) {
>             throw new BluetoothAdapterSnippetException("Failed to become discoverable.");
> ```

If bluetooth is off, this is the message that gets printed, which isn't really debugging-friendly. Any chance we can check the current bt state to give a better error message if it's off?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 163 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj5zpFj7HxCJV9RGSNz:-Kj5zpFj7HxCJV9RGSO-:bjbojx) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L163)):*
> ```Java
>                             mBluetoothAdapter
>                                     .getClass()
>                                     .getDeclaredMethod("setScanMode", int.class, int.class)
> ```

When were these methods created? Have they ever changed?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 196 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj5zaiPkkwWJ_FBep-N:-Kj5zaiQwPLzC4fTwFc5:brr01az) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L196)):*
> ```Java
>     @RpcMinSdk(Build.VERSION_CODES.KITKAT)
>     @Rpc(description = "Enable Bluetooth HCI snoop log for debugging.")
>     public boolean btEnableHciSnoopLog() throws Throwable {
> ```

Sorry for missing this the first time around; these should not be returning booleans. Same with disableHciSnoopLog. (How did this get written this way originally? We don't have that style anywhere else in the code...) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41)*

**Comment by xpconanfan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 108 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj5zLeer3-_EQBVIXAY:-Kj60kyJy2udXmLzHbTI:b-kl8h9p) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L108)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

When I executed this method, it only returned one element and then threw up a bluetooth pairing request which interrupted the UI. When I ran it again it seemingly succeeded. Do you see the same thing when you run it?
</blockquote></details>

I don't see that. I'm able to run this just fine.
Which build version are you using.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 163 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj5zpFj7HxCJV9RGSNz:-Kj6-wRl0NtdVT2HHcaV:bezoeln) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L163)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

When were these methods created? Have they ever changed?
</blockquote></details>

This has been there since the beginning as far as i could tell.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 196 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj5zaiPkkwWJ_FBep-N:-Kj60SpGDGENbIJYm9K8:bxy2gp9) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L196)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Sorry for missing this the first time around; these should not be returning booleans. Same with disableHciSnoopLog. (How did this get written this way originally? We don't have that style anywhere else in the code...) 
</blockquote></details>

Because this is a debug log switch so I didn't want this to throw by default, because this is a best-effort thing as it is not guaranteed that a device would support this log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41)*

**Comment by xpconanfan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 151 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj6-BnaTO0vcN7kRlft:-Kj61iXhJdDS_CebUypT:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L151)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

If bluetooth is off, this is the message that gets printed, which isn't really debugging-friendly. Any chance we can check the current bt state to give a better error message if it's off?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41)*

**Comment by adorokhine** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/AndroidManifest.xml, line 19 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj63334sM7CWWSRWX7e:-Kj63334sM7CWWSRWX7f:b-373nes) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eeb3e0543a8efa5e79cbba5e7876ddffa797190f/src/main/AndroidManifest.xml#L19)):*
> ```XML
>     <uses-permission android:name="android.permission.READ_SYNC_SETTINGS"/>
>     <uses-permission android:name="android.permission.WRITE_SETTINGS" />
>     <uses-permission android:name="android.permission.WRITE_SECURE_SETTINGS" />
> ```

The Android documentation says this is not for third-party apps:
https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SECURE_SETTINGS

And stackoverflow suggests adding it to manifest does nothing:
http://stackoverflow.com/a/13045819/1612937

Are you sure this line is doing what you think it's doing?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 108 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj5zLeer3-_EQBVIXAY:-Kj63NNKuhnr5S1tqSVR:b-oqqzc7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/86c54e40e3f0eb61b6a341e47b8188c45ed2d7b6/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L108)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I don't see that. I'm able to run this just fine.
Which build version are you using.
</blockquote></details>

Happened to be testing on LVY47H.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/AndroidManifest.xml, line 19 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-Kj63334sM7CWWSRWX7e:-Kj6AYjW2kL_898TcSuX:ba3dfob) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/eeb3e0543a8efa5e79cbba5e7876ddffa797190f/src/main/AndroidManifest.xml#L19)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

The Android documentation says this is not for third-party apps:
https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SECURE_SETTINGS

And stackoverflow suggests adding it to manifest does nothing:
http://stackoverflow.com/a/13045819/1612937

Are you sure this line is doing what you think it's doing?
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/41#-:-Kj6IN9s4hSRigH2PK3r:bnfp4nl)*

**Pull request merged**
