### PR TITLE
Allow calling wifiConnect with the connected network.

### PR DESCRIPTION
**Pull request by xpconanfan**
* also fix lint in AccountSnippet.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/28)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 127 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-Kf8MdALtq4FqPNC633f:-Kf8MdALtq4FqPNC633g:b-ewnszd) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L127)):*
> ```Java
>     public void wifiConnectSimple(String ssid, @Nullable String password)
>             throws InterruptedException, JSONException, WifiManagerSnippetException {
>         String currentSsid =
> ```

Why do this only in wifiConnectSimple? Also, wouldn't still have an error if we request to connect to an already "added" but not connected SSID?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 128 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-Kf8NGKyFxUlcKkGpHC7:-Kf8NGKzyUcAXPt_ks1A:b-4stxug) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L128)):*
> ```Java
>             throws InterruptedException, JSONException, WifiManagerSnippetException {
>         String currentSsid =
>                 JsonSerializer.trimQuotationMarks(mWifiManager.getConnectionInfo().getSSID());
> ```

Why would this string be quoted? Spaces are handled fine by String...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by xpconanfan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 127 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-Kf8MdALtq4FqPNC633f:-Kf8NQjfvMlgMUdE0AZ5:b-xhb2bi) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L127)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Why do this only in wifiConnectSimple? Also, wouldn't still have an error if we request to connect to an already "added" but not connected SSID?
</blockquote></details>

Because wifiConnected is for more advanced usage and this one is for simple straightforward usages. So I'd want to keep the checks here.

I see, a network could be added yet not connected, hmm...

So I guess the expected behavior for `wifiConnectSimple` is to delete the added network, add the new config for the network, then connect with the new config? E.g. if a network has a new password, call `wifiConnectSimple` again with the new password should work.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 128 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-Kf8NGKyFxUlcKkGpHC7:-Kf8NUvm_fZCEgiK6RC2:bq4vdm9) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L128)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Why would this string be quoted? Spaces are handled fine by String...
</blockquote></details>

I think the SSID in `WifiConnectionInfo` is automatically quoted by Android...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by dthkao** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 127 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-Kf8MdALtq4FqPNC633f:-Kf90aHxM-cQhTRS3pcJ:b-kodbp8) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L127)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Because wifiConnected is for more advanced usage and this one is for simple straightforward usages. So I'd want to keep the checks here.

I see, a network could be added yet not connected, hmm...

So I guess the expected behavior for `wifiConnectSimple` is to delete the added network, add the new config for the network, then connect with the new config? E.g. if a network has a new password, call `wifiConnectSimple` again with the new password should work.
</blockquote></details>

sgtm. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 130 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfAqBl3cMnoLuL-pQIZ:-KfAqBl5wAt_sFBLqmiV:b-sad3xk) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L130)):*
> ```Java
>                 JsonSerializer.trimQuotationMarks(mWifiManager.getConnectionInfo().getSSID());
>         if (ssid.equals(currentSsid)) {
>             return;
> ```

Can we add a log here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by xpconanfan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 127 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-Kf8MdALtq4FqPNC633f:-KfDXKdG8vQZ3nlTjKq2:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L127)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

sgtm. 
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 130 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfAqBl3cMnoLuL-pQIZ:-KfDXLVTFaYyvd1tfphP:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c730fb19d665ef1eb418cbf0dd12f53a02e2cb2/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L130)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can we add a log here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 143 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDYd9WQap5eh0L_MJH:-KfDYd9XlQUNlcNI9cOP:binda5j) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L143)):*
> ```Java
>      * WifiManager}.addNetwork.
>      */
>     private WifiConfiguration getExistingConfiguredNetwork(String ssid) {
> ```

We don't need to strip quotes anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 143 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDYd9WQap5eh0L_MJH:-KfDZD4BsKqOgGv9JKyF:br2kup1) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L143)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

We don't need to strip quotes anymore?
</blockquote></details>

This is comparing config with config, so both sides have quotes here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 1 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZ4vBPvniUCKAFJAS:-KfDZ4vBPvniUCKAFJAT:b-b6ywpw) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L1)):*
> ```Java
> /*
> ```

What does AccountSnippet have to do with wifiConnect?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 141 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZEJxDtG4QBzTvlVR:-KfDZEJxDtG4QBzTvlVS:b-nkvvl0) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L141)):*
> ```Java
>      *
>      * <p>A network is configured if a WifiConfiguration was created for it and added with {@link
>      * WifiManager}.addNetwork.
> ```

{@link WifiManager#addNetwork()} ... studio should fill this in automatically once you hit #

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 54 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZSqPJuOR0RWGwKq9:-KfDZSqQi7vTRn_iuSBJ:beff9so) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L54)):*
> ```Java
>      * @param originalString
>      */
>     public static String trimQuotationMarks(String originalString) {
> ```

Newly exposed method not used externally?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 1 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZ4vBPvniUCKAFJAS:-KfD_3PKV1FS-5f05JcC:b-u51cdp) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L1)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

What does AccountSnippet have to do with wifiConnect?
</blockquote></details>

All changes in this file are linter changes.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 141 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZEJxDtG4QBzTvlVR:-KfD_IX5J-bjKhdLJyFl:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L141)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

{@link WifiManager#addNetwork()} ... studio should fill this in automatically once you hit #
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 54 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZSqPJuOR0RWGwKq9:-KfD_QkhZiwFxogZUN73:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L54)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Newly exposed method not used externally?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 1 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZ4vBPvniUCKAFJAS:-KfDd8b_n-D00e7AlHTf:b-2pmklz) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L1)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

All changes in this file are linter changes.
</blockquote></details>

Why are we running the linter on unrelated files? Let's do it separately from this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 1 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZ4vBPvniUCKAFJAS:-KfDlgsU77UuBvMHSdPE:b3t0tpl) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L1)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Why are we running the linter on unrelated files? Let's do it separately from this PR.
</blockquote></details>

The linter automatically runs on all files.
Is there a way for it not to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 141 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZEJxDtG4QBzTvlVR:-KfDszeHzdSA8csYi0I0:b3mjdv4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L141)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No new commit uploaded?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 141 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDZEJxDtG4QBzTvlVR:-KfDtHoziMFN21Nfz0cO:bapgzrh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7798ecd9334673cc912798b2b415b289002d0dd4/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L141)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

No new commit uploaded?
</blockquote></details>

Done and rebased. Thx!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 167 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDu7xhIOa133LnNCBr:-KfDu7xiq9Z_fvMeZiuq:b-arbpi7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7c931c67c162d95e350a10b2a31747425551bf56/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L167)):*
> ```Java
>         WifiConfiguration wifiConfig = JsonDeserializer.jsonToWifiConfig(wifiNetworkConfig);
>         // Return directly if network is already connected.
>         String connectedSsid = mWifiManager.getConnectionInfo().getSSID();
> ```

What does wifiManager.getConnectionInfo() return if no connection exists? This won't crash?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 167 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-KfDu7xhIOa133LnNCBr:-KfDvcq2wsJ-QaFuO3cM:b-p1n4cv) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7c931c67c162d95e350a10b2a31747425551bf56/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L167)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

What does wifiManager.getConnectionInfo() return if no connection exists? This won't crash?
</blockquote></details>

it returns a WifiConnectionInfo object with default values.
Default SSID is '0x'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/28#-:-KfE1HnPSGgZmkB7753e:bnfp4nl)*

**Pull request merged**
