### PR TITLE
Added getTelephonyServiceState() to TelephonySnippet

### PR DESCRIPTION
**Pull request by k2fong**
Added capability is intended to replace an existing service state that uses output from dumpsys telephony.registry

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/77)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 54 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-KseyPjKmoub7DBFxj1M:-KseyPjKmoub7DBFxj1N:b5ok7eg) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d7f12e6c80a32fd0a78ab842eedbe1585c4f6adc/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L54)):*
> ```Java
>     }
> 
>     @Rpc(
> ```

This is going to need @RpcMinSdk. It's 26 i believe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 57 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-Ksf5yvS_IZ0NtchDxR8:-Ksf5yvS_IZ0NtchDxR9:bxdadjh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d7f12e6c80a32fd0a78ab842eedbe1585c4f6adc/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L57)):*
> ```Java
>         description =
>                 "Returns the current Service State information. Service state values are "
>                         + "0: STATE_IN_SERVICE, "
> ```

let's not repeat the constants here.
A better approach is to point users to where the macros are defined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 54 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-KseyPjKmoub7DBFxj1M:-KsivN9XwhuLbSz6Cjsv:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d7f12e6c80a32fd0a78ab842eedbe1585c4f6adc/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L54)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

This is going to need @RpcMinSdk. It's 26 i believe?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 57 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-Ksf5yvS_IZ0NtchDxR8:-KsivNcQKE0toDgunD6C:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d7f12e6c80a32fd0a78ab842eedbe1585c4f6adc/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L57)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

let's not repeat the constants here.
A better approach is to point users to where the macros are defined
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 61 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-KstxW2Z20lBpCFfFN_g:-KstxW2Z20lBpCFfFN_h:b-9icyk4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9556ace235eac43a422669a5b654967ea2b28d41/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L61)):*
> ```Java
>      */
>     @Rpc(description = "Returns the current Service State information")
>     @RpcMinSdk(Build.VERSION_CODES.O)
> ```

does this compile?
I don't see `O` being an option in my IDE.
Did you have to change gradle config to make this work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77)*

**Comment by k2fong** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 61 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-KstxW2Z20lBpCFfFN_g:-KsuTSQ1GcYijQBo31Hl:b-p748ay) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9556ace235eac43a422669a5b654967ea2b28d41/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

does this compile?
I don't see `O` being an option in my IDE.
Did you have to change gradle config to make this work?
</blockquote></details>

hmm maybe because I used --android_sdk=//third_party/java/android/android_sdk_linux/platforms/stable_system:android_sdk_tools

I tested it on citc client

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 61 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-KstxW2Z20lBpCFfFN_g:-KsuUi08LQv50ZfOlkNh:b-9utxwc) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9556ace235eac43a422669a5b654967ea2b28d41/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L61)):*
<details><summary><i>Previously, k2fong wrote…</i></summary><blockquote>

hmm maybe because I used --android_sdk=//third_party/java/android/android_sdk_linux/platforms/stable_system:android_sdk_tools

I tested it on citc client
</blockquote></details>

1. do not mention internal path in public code review
2. you need to verify in public tool chain if you want to check it into public repo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, line 61 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77#-KstxW2Z20lBpCFfFN_g:-KsuVVs7wxqcftudM_xz:bb7p34n) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9556ace235eac43a422669a5b654967ea2b28d41/src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

1. do not mention internal path in public code review
2. you need to verify in public tool chain if you want to check it into public repo
</blockquote></details>

test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/77)*

**Pull request closed without merging**
