### PR TITLE
Simplify API required to call methods by reflection.

### PR DESCRIPTION
**Pull request by adorokhine**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/45)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6YiaQPCbur03h5Qva:-Kj6YiaQPCbur03h5Qvb:b1hfff1) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32d05753767fe30ebb4d0fe20da52f22dfefa93d/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L29)):*
> ```Java
>      * going on.
>      */
>     public interface Predicate {
> ```

why was this moved in order? is there a particular convention we are trying to follow by moving this?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 65 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6ZNwqlJTudC78O_Qq:-Kj6ZNwqlJTudC78O_Qr:b6gb6ij) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32d05753767fe30ebb4d0fe20da52f22dfefa93d/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L65)):*
> ```Java
>     }
> 
>     public static Object invokeByReflection(Object instance, String methodName, Object... args)
> ```

Need Javadoc for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45)*

**Comment by adorokhine** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6YiaQPCbur03h5Qva:-Kj6fe2Hf2HdHg07ZlZC:b-jgv61q) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32d05753767fe30ebb4d0fe20da52f22dfefa93d/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L29)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

why was this moved in order? is there a particular convention we are trying to follow by moving this?
</blockquote></details>

You're right, the documented convention is actually footnote/endnote style, which seems strange to me but ok. Moved back.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 65 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6ZNwqlJTudC78O_Qq:-Kj6gmmr9Ggnly6bsojK:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32d05753767fe30ebb4d0fe20da52f22dfefa93d/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L65)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Need Javadoc for this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45)*

**Comment by xpconanfan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java, line 81 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6il3L-eBj_TqgqyaS:-Kj6il3L-eBj_TqgqyaT:b9i8we4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java#L81)):*
> ```Java
>         Class<?> audioSystem = Class.forName("android.media.AudioSystem");
>         Method getNumStreamTypes = audioSystem.getDeclaredMethod("getNumStreamTypes");
>         int numStreams = (int) getNumStreamTypes.invoke(null /* instance */);
> ```

could we not use the new util for this reflection call?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 67 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6is6-5oP6i-azYlkH:-Kj6is6-5oP6i-azYlkI:b72ytcy) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L67)):*
> ```Java
>     /**
>      * Simplified API to invoke an instance method by reflection.
>      *
> ```

Can we add a piece of sample code showing the usage in javadoc?

---

*[src/test/java/UtilsTest.java, line 68 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6jOHCErxi-l8cEPC3:-Kj6jOHCErxi-l8cEPC4:bfkjmip) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/test/java/UtilsTest.java#L68)):*
> ```Java
> 
>     @Test
>     public void testInvokeByReflection_Primitive() throws Throwable {
> ```

Can we add unit tests for non-primitive type and passing multiple args?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45)*

**Comment by adorokhine** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java, line 81 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6il3L-eBj_TqgqyaS:-Kj6oeSo1uxBGMFrhyfi:b-z5a34u) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java#L81)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

could we not use the new util for this reflection call?
</blockquote></details>

We can't right now because this is a static method call and the util only supports instance method calls (instance.getClass().getMethods()). It's possible to support static calls but it would be a separate method, and this code is very short, so I'm hopeful to avoid it for the time being.

---

*[src/test/java/UtilsTest.java, line 68 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6jOHCErxi-l8cEPC3:-Kj6oy7tyAocaLKncjHQ:b-o6s0rb) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/test/java/UtilsTest.java#L68)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Can we add unit tests for non-primitive type and passing multiple args?
</blockquote></details>

There already is one for non-primitive type (`testInvokeByReflection_Obj`), is that insufficient?
I'll add one for passing multiple args.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45)*

**Comment by xpconanfan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/java/UtilsTest.java, line 68 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6jOHCErxi-l8cEPC3:-Kj7-DT9bkONT7TbjA7U:b-8ukb7g) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/test/java/UtilsTest.java#L68)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

There already is one for non-primitive type (`testInvokeByReflection_Obj`), is that insufficient?
I'll add one for passing multiple args.
</blockquote></details>

Oops, I missed that.
Could we put the Obj one after Null and NoArg? The order threw me off a bit.
And could we add a multi-arg one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45)*

**Comment by adorokhine** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/java/UtilsTest.java, line 68 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6jOHCErxi-l8cEPC3:-Kj73yTbXJnnNIuz0Zcn:b3insb2) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/test/java/UtilsTest.java#L68)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Oops, I missed that.
Could we put the Obj one after Null and NoArg? The order threw me off a bit.
And could we add a multi-arg one?
</blockquote></details>

You want to put the regular happy path test AFTER the corner case special value test? I can reorder it however you want, but that seems pretty unintuitive to me. testInvokeByReflection_Obj will represent the most common code path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/java/UtilsTest.java, line 68 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6jOHCErxi-l8cEPC3:-Kj7937lPo1XgaHT5xec:b-wgi3ck) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/test/java/UtilsTest.java#L68)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

You want to put the regular happy path test AFTER the corner case special value test? I can reorder it however you want, but that seems pretty unintuitive to me. testInvokeByReflection_Obj will represent the most common code path.
</blockquote></details>

Ok, common case in the front makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-:-Kj798UcA_3ObMUoq--Z:bnfp4nl)*

**Comment by adorokhine** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 67 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6is6-5oP6i-azYlkH:-KjACz8UsdfJKjULxO1o:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L67)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Can we add a piece of sample code showing the usage in javadoc?
</blockquote></details>

Done.

---

*[src/test/java/UtilsTest.java, line 68 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-Kj6jOHCErxi-l8cEPC3:-KjAHsQnCdUJcDuKrjGr:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5c53d7c82ca796897ffe67e5a5872043d7285ca5/src/test/java/UtilsTest.java#L68)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Ok, common case in the front makes sense.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/45#-:-KjAcd4BELzDmbiH4hd2:bnfp4nl)*

**Pull request merged**
