### PR TITLE
SmsSnippet cleanup

### PR DESCRIPTION
**Pull request by arammelk**
Cleanup style stuff in SmsSnippet

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/72)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 82 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72#-KqPaC_c5ekLvgqzcy5B:-KqPaC_c5ekLvgqzcy5C:bkxmvvr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8efb6ca73fa2b4148bc456ff0db7bf28138fa5b0/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L82)):*
> ```Java
>     public void sendSms(String phoneNumber, String message)
>             throws InterruptedException, SmsSnippetException {
>         String callbackId = new StringBuilder().append(SMS_CALLBACK_ID_PREFIX)
> ```

AS reports that it's more efficient to use simple string concatenation here.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 106 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72#-KqPaSLx_HVmP4Witwq3:-KqPaSLx_HVmP4Witwq4:b-36186m) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8efb6ca73fa2b4148bc456ff0db7bf28138fa5b0/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L106)):*
> ```Java
>         String qId = EventCache.getQueueId(callbackId, SMS_SENT_EVENT_NAME);
>         LinkedBlockingDeque<SnippetEvent> q = EventCache.getInstance().getEventDeque(qId);
>         SnippetEvent result = q.pollFirst(DEFAULT_TIMEOUT_MILLISECOND, TimeUnit.MILLISECONDS);
> ```

`InterruptedException` seems closely related to the implementation details of this method.
Should we catch it here and throw an exception with more informative message here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 82 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72#-KqPaC_c5ekLvgqzcy5B:-KqQA7U0y-9kZ94FBm9g:b-hdf8le) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8efb6ca73fa2b4148bc456ff0db7bf28138fa5b0/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L82)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

AS reports that it's more efficient to use simple string concatenation here.
</blockquote></details>

Let's use simple '+' here since it's only two Strings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72)*

**Comment by arammelk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 82 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72#-KqPaC_c5ekLvgqzcy5B:-KqQAMDcZ2ApJNo-3v72:b-st99fa) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8efb6ca73fa2b4148bc456ff0db7bf28138fa5b0/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L82)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Let's use simple '+' here since it's only two Strings?
</blockquote></details>

Done. Where in AS do you see this, I want to enable it so I can catch it before sending out for review :)

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 106 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72#-KqPaSLx_HVmP4Witwq3:-KqQ9zmpOqROk_Nm7V7-:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8efb6ca73fa2b4148bc456ff0db7bf28138fa5b0/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L106)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

`InterruptedException` seems closely related to the implementation details of this method.
Should we catch it here and throw an exception with more informative message here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 82 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72#-KqPaC_c5ekLvgqzcy5B:-KqQAsJfk2HAxNfOY6z3:bnxnrlg) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/8efb6ca73fa2b4148bc456ff0db7bf28138fa5b0/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L82)):*
<details><summary><i>Previously, arammelk wrote…</i></summary><blockquote>

Done. Where in AS do you see this, I want to enable it so I can catch it before sending out for review :)
</blockquote></details>

Warnings are highlighted for me in my view. Not sure if it's the same for everybody.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72)*

**Comment by xpconanfan** [comment]
:lgtm:

Thanks!!
Good to go as long as `./gradlew goJF` were run. :)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/72#-:-KqQBR6Lg9rkiPKMOI3z:b-7wj40g)*

**Pull request merged**
