### PR TITLE
Add Wi-Fi soft ap related Rpc methods.

### PR DESCRIPTION
**Pull request by xpconanfan**
Also a change in wait util to accomodate lambda functions that
throw exceptions, which interrupt the wait.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/35)

### CODE REVIEW

**Comment by adorokhine** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 245 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhP_rVlkFbwK62tmmUV:-KhP_rVm015MmLnt3KK4:byf7tp1) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L245)):*
> ```Java
>     @Rpc(description = "Check whether Wi-Fi Soft AP (hotspot) is enabled.")
>     public boolean wifiIsApEnabled()
>             throws IllegalAccessException, InvocationTargetException, NoSuchMethodException {
> ```

Should we rethrow the cause of InvocationTargetException to get a shorter, simpler stacktrace?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 251 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPa80UNoniKP693Z02:-KhPa80VkDrHjoG9rhO8:b-becr8o) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L251)):*
> ```Java
> 
>     @Rpc(description = "Enable or disable Wi-Fi Soft AP (hotspot).")
>     public void wifiSetApEnabled(Boolean enable)
> ```

Are we able to pass primitives yet? I thought you added some code to do this

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 260 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPaJN-jNOlMa6H0Rai:-KhPaJN-jNOlMa6H0Raj:b-p4jr3p) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L260)):*
> ```Java
>                                 .getDeclaredMethod(
>                                         "setWifiApEnabled", WifiConfiguration.class, boolean.class)
>                                 .invoke(mWifiManager, null, enable);
> ```

Mind adding a `/* callsite comment */` to that `null`?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPaV7qe6SUxEfnueA9:-KhPaV7rmE8JxngfOP6b:b-4y5ir7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L29)):*
> ```Java
>      *
>      * <p>If the predicate function throws an exception and interrupts the waiting, the exception
>      * will be wrapped in an {@link InterruptedException}.
> ```

InterruptedException has a pretty specific meaning and may cause downstream code to re-issue the interrupt onto other threads it's managing (via `thread.interrupt()`); how about RuntimeException? Or declaring a new exception type for this purpose?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 50 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPayZ2woIsILwMQd4N:-KhPayZ2woIsILwMQd4O:b-dk1fl6) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L50)):*
> ```Java
>         } catch (Exception e) {
>             throw new InterruptedException(
>                     "Waiting was interrupted because: "
> ```

You seem to be emulating Java's normal exception cause mechanism by formatting the cause into a string of the exception's message. Just let the cause through in the constructor like normal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 245 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhP_rVlkFbwK62tmmUV:-KhPblhG6Rd9NM7uXElL:b-bbo5je) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L245)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Should we rethrow the cause of InvocationTargetException to get a shorter, simpler stacktrace?
</blockquote></details>

Sorry, not sure what you mean by "rethrow".

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 251 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPa80UNoniKP693Z02:-KhPflW19-4XlOyEKFQF:bs59cr4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L251)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Are we able to pass primitives yet? I thought you added some code to do this
</blockquote></details>

I just realized this should be split into two methods instead.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 260 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPaJN-jNOlMa6H0Rai:-KhPgjROSUPUzwXMNd3s:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L260)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Mind adding a `/* callsite comment */` to that `null`?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPaV7qe6SUxEfnueA9:-KhPgioDQsAaYd_znI9t:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L29)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

InterruptedException has a pretty specific meaning and may cause downstream code to re-issue the interrupt onto other threads it's managing (via `thread.interrupt()`); how about RuntimeException? Or declaring a new exception type for this purpose?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 50 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPayZ2woIsILwMQd4N:-KhPgi-v4T3XDUFgTI4l:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L50)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

You seem to be emulating Java's normal exception cause mechanism by formatting the cause into a string of the exception's message. Just let the cause through in the constructor like normal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by adorokhine** [comment]
Reviewed 3 of 4 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 2 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPma9LBOJ1RVK5P49w:-KhPma9LBOJ1RVK5P49x:b-bx1yu0) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L2)):*
> ```Java
> /*
>  * Copyright (C) 2017 Google Inc.
> ```

You have a different PR that fixes issues with the bt snippet right? Can you do the reformat there instead? Or separately in its own PR?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 245 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhP_rVlkFbwK62tmmUV:-KhPmfpcp8Dy0JU2Ge1F:b3qtk1h) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L245)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Sorry, not sure what you mean by "rethrow".
</blockquote></details>

`
try {
  ...
} catch (InvocationTargetException e) {
  throw e.getCause();
}
`

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 251 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPmqaG3S2SUvF3CC_m:-KhPmqaHu973vGA36rQN:b-cvg95a) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L251)):*
> ```Java
> 
>     @Rpc(description = "Enable Wi-Fi Soft AP (hotspot).")
>     public void wifiEnableSoftAp(@Nullable JSONObject configuration)
> ```

Can you add a javadoc describing what the configuration object should contain?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 290 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPn6hH5Il_rPK9I276:-KhPn6hH5Il_rPK9I277:bkst12s) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L290)):*
> ```Java
>                                         "setWifiApEnabled", WifiConfiguration.class, boolean.class)
>                                 .invoke(
>                                         mWifiManager, /* No configuration needed for disabling */
> ```

Callsite comment attached to the wrong param?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 29 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPnN07JBi_wYIvGhXS:-KhPnN082rZKKK0WFT-m:bbmauqx) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L29)):*
> ```Java
>      *
>      * <p>If the predicate function throws an exception and interrupts the waiting, the exception
>      * will be wrapped in an {@link InterruptedException}.
> ```

Comment and `@throws` out of date

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 38 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPnPUfCuyQyeENxC1G:-KhPnPUfCuyQyeENxC1H:bxf55oh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L38)):*
> ```Java
>      */
>     public static boolean waitUntil(Utils.Predicate predicate, int timeout)
>             throws RuntimeException {
> ```

Runtime exceptions shouldn't be in the 'throws' line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by xpconanfan** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 2 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPma9LBOJ1RVK5P49w:-KhPpirhizyX6B0Ccsvj:b-q74z3n) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L2)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

You have a different PR that fixes issues with the bt snippet right? Can you do the reformat there instead? Or separately in its own PR?
</blockquote></details>

Can rebase after the other is done, whichever PR gets in first.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 245 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhP_rVlkFbwK62tmmUV:-KhPpq2WyaMG8iUUvjP6:b-rsdk0b) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L245)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

`
try {
  ...
} catch (InvocationTargetException e) {
  throw e.getCause();
}
`
</blockquote></details>

Hmm, we don't do that in snippet lib though, do we?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 251 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPmqaG3S2SUvF3CC_m:-KhPqxQCZRmDyO7BekE7:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L251)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can you add a javadoc describing what the configuration object should contain?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 290 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPn6hH5Il_rPK9I276:-KhPqNHvF2c-0JUotoSZ:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L290)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Callsite comment attached to the wrong param?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 29 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPnN07JBi_wYIvGhXS:-KhPqIJYqEGQALDwugua:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L29)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Comment and `@throws` out of date
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 38 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPnPUfCuyQyeENxC1G:-KhPqD0nH8vR2WHvJd8K:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L38)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Runtime exceptions shouldn't be in the 'throws' line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by dthkao** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, line 29 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPnN07JBi_wYIvGhXS:-KhPsZWdlVuhAiAzfgNQ:b-u321j8) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java#L29)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Comment still refers to InterruptedException?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by xpconanfan** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 245 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhP_rVlkFbwK62tmmUV:-KhTEkn5u8_D6PwqAUoW:b-uxgy9g) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/73d9ed0e4d8a25f6e6366db337be161c70ddf9ea/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L245)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, we don't do that in snippet lib though, do we?
</blockquote></details>

Got it.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by adorokhine** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, line 2 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhPma9LBOJ1RVK5P49w:-KhU-r7Mw0ol5aZoGC0I:b3y43k5) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a16cc8cb6b660d03aab687c6f298fb308b907a21/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java#L2)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Can rebase after the other is done, whichever PR gets in first.
</blockquote></details>

The other one please, since this PR has nothing to do with BluetoothAdapterSnippet.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 247 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhTzhYwyd1nOmYIQ1yK:-KhTzhYwyd1nOmYIQ1yL:bzc90lx) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/206a3d0d248a86d6bc885b3c29fd2b481f25441a/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L247)):*
> ```Java
>             throws IllegalAccessException, InvocationTargetException, NoSuchMethodException {
>         return (boolean)
>                 mWifiManager.getClass().getDeclaredMethod("isWifiApEnabled").invoke(mWifiManager);
> ```

Should we catch and unwrap the invocationtargetexception here too?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 253 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhU-RJRWIaaxLYsqCTn:-KhU-RJRWIaaxLYsqCTo:b-k1pb2l) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/206a3d0d248a86d6bc885b3c29fd2b481f25441a/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L253)):*
> ```Java
>      * Enable Wi-Fi Soft AP (hotspot).
>      *
>      * <p>Does not work for release N.
> ```

What error do you get on N? Is it nice enough already or should we check the sdk level and throw our own one explaining N is unsupported for this call?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by xpconanfan** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 247 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhTzhYwyd1nOmYIQ1yK:-Ki6RwjiYvOy8vgTHXiI:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/206a3d0d248a86d6bc885b3c29fd2b481f25441a/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L247)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Should we catch and unwrap the invocationtargetexception here too?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 253 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KhU-RJRWIaaxLYsqCTn:-Ki6RxCC9kZDZ9-uzjH5:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/206a3d0d248a86d6bc885b3c29fd2b481f25441a/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L253)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

What error do you get on N? Is it nice enough already or should we check the sdk level and throw our own one explaining N is unsupported for this call?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by xpconanfan** [comment]
Ping

**Comment by adorokhine** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 305 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KiftIRHAShwJF20YgXE:-KiftIRHAShwJF20YgXF:b34fuaa) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9d0f6dfe0e0b24030f7893a8fd96680621c6449f/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L305)):*
> ```Java
>         if (!Utils.waitUntil(() -> wifiIsApEnabled() == true, 60)) {
>             throw new WifiManagerSnippetException(
>                     "Timed out after 60 waiting for Wi-Fi Soft AP state to turn on with configuration: "
> ```

Could we add a time unit here? It just says "timed out after 60" (here and elsewhere)

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/ApiVersionException.java, line 4 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KiftYgpdcsSrG20sJsa:-KiftYgpdcsSrG20sJsb:b1m5ryf) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9d0f6dfe0e0b24030f7893a8fd96680621c6449f/src/main/java/com/google/android/mobly/snippet/bundled/utils/ApiVersionException.java#L4)):*
> ```Java
> 
> /** Raised for when an Rpc call is not supported by the Android version used. */
> public class ApiVersionException extends Exception {
> ```

Does our @RpcMinSdk annotation throw something if you try to call it with an invalid sdk? If so, what does it throw, and should it be changed to this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 305 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KiftIRHAShwJF20YgXE:-Kig1qoNCZpUbjyHw7sE:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9d0f6dfe0e0b24030f7893a8fd96680621c6449f/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L305)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Could we add a time unit here? It just says "timed out after 60" (here and elsewhere)
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/ApiVersionException.java, line 4 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KiftYgpdcsSrG20sJsa:-Kig1YlFjQOS3TOBv06N:b-pht29q) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9d0f6dfe0e0b24030f7893a8fd96680621c6449f/src/main/java/com/google/android/mobly/snippet/bundled/utils/ApiVersionException.java#L4)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Does our @RpcMinSdk annotation throw something if you try to call it with an invalid sdk? If so, what does it throw, and should it be changed to this?
</blockquote></details>

That would be a change in snippet lib, so it can't be done in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by adorokhine** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 305 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KiftIRHAShwJF20YgXE:-KigEyFED6UzNca3Vdwy:b-fmbiw5) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9d0f6dfe0e0b24030f7893a8fd96680621c6449f/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L305)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

By "here and elsewhere" I meant "this problem exists at this location in the code, and also exists in other places in the CL which should also be fixed".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by xpconanfan** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, line 305 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-KiftIRHAShwJF20YgXE:-KigFlrueZqtkq36bpvS:byhc6ut) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/9d0f6dfe0e0b24030f7893a8fd96680621c6449f/src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java#L305)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

By "here and elsewhere" I meant "this problem exists at this location in the code, and also exists in other places in the CL which should also be fixed".
</blockquote></details>

Done.
Not sure how many you see. Would be nice to mention how many or which files you are seeing them in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/35#-:-KigLQEalTeIGn7qAmBY:bnfp4nl)*

**Pull request merged**
