### PR TITLE
Add Rpcs for basic Android logging.

### PR DESCRIPTION
**Pull request by xpconanfan**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/52)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 27 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlXsikx_V1UxKuL4o4Y:-KlXsikyFWsSLK8_-YEE:b4y0jy9) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d476ff603f025843f03e9651693461a253c9f21d/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L27)):*
> ```Java
> 
>     @Rpc(description = "Log at info level.")
>     public void logI(String tag, String message) {
> ```

Why not set the tag to "MBS"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 27 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlXsikx_V1UxKuL4o4Y:-KlZGTpTOyVfCKuka4hK:bxyyau4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d476ff603f025843f03e9651693461a253c9f21d/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L27)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Why not set the tag to "MBS"?
</blockquote></details>

This exposes the android utils logger.
And test writers probably want to have their own tags.
E.g. in my use case, i'd like to use a tag relevant to my tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 27 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlXsikx_V1UxKuL4o4Y:-KlZJv_U2F_29GXB8nnS:b8nvpe) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d476ff603f025843f03e9651693461a253c9f21d/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L27)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This exposes the android utils logger.
And test writers probably want to have their own tags.
E.g. in my use case, i'd like to use a tag relevant to my tests.
</blockquote></details>

Would something besides the test be using the MBS logger rpcs besides your test? In most uses I don't see the longer signature being helpful.

How about an Rpc in this snippet class to set the tag rather than passing it in every time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 27 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlXsikx_V1UxKuL4o4Y:-KlZT1H2VJVEsZ5sqP1S:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/d476ff603f025843f03e9651693461a253c9f21d/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L27)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Would something besides the test be using the MBS logger rpcs besides your test? In most uses I don't see the longer signature being helpful.

How about an Rpc in this snippet class to set the tag rather than passing it in every time?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-KlZXB1gdbvf48QDDiap:b-sq7sbe) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
> ```Java
> /** Snippet class exposing Android APIs related to logging. */
> public class LogSnippet implements Snippet {
>     private static String mTag = "MBS";
> ```

Should this be static? It seems odd with the setter function being a non-static Rpc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-KlZaGd8gIiexS9yYZu8:bdcj0v6) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Should this be static? It seems odd with the setter function being a non-static Rpc.
</blockquote></details>

there's only one instance of this in MBS.

We have a lot of these, like all the exception inner classes are static, but the methods that throw them are not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-Klb0I2jOMJiIwwsV5Rm:b-fowluo) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

there's only one instance of this in MBS.

We have a lot of these, like all the exception inner classes are static, but the methods that throw them are not
</blockquote></details>

Static nested classes are different. With this we are allowing an object to set the class variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-Klb8vIltUw11ElcerZF:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Static nested classes are different. With this we are allowing an object to set the class variable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by dthkao** [comment]
LGTM, but check if Alex has comments too.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-:-KlbnjjW-GNF3jPtAwwX:bhtgu2l)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-KlbojuTkiEh8xprL3sM:bp1rezz) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think MBS's own log messages (logged through snippet.util.log) will have a different tag, probably `com.google.android.mobly.snippet.bundled`:
https://github.com/google/mobly-snippet-lib/blob/3797ad61618f23003445805a0545cf8d2bc08e94/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java#L26

Are we ok with LogSnippet logging with tag `MBS` but other snippets logging with tag `com.google.android.mobly.snippet.bundled`? Seems a little surprising to me.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 58 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-Klbockq_rbcy-ZAVuFL:-Klbockr-wjG3XI1vikY:b-o73sz0) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a509ff093c5044a4d0044c6124cc346fafc5f151/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L58)):*
> ```Java
> 
>     @Rpc(description = "Log at WTF level.")
>     public void logWTF(String message) {
> ```

Per https://source.android.com/source/code-style "Treat Acronyms As Words", should be `logWtf`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-KldwvkZpLxLEVRwT0zO:b-ratib8) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I think MBS's own log messages (logged through snippet.util.log) will have a different tag, probably `com.google.android.mobly.snippet.bundled`:
https://github.com/google/mobly-snippet-lib/blob/3797ad61618f23003445805a0545cf8d2bc08e94/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java#L26

Are we ok with LogSnippet logging with tag `MBS` but other snippets logging with tag `com.google.android.mobly.snippet.bundled`? Seems a little surprising to me.
</blockquote></details>

This is not MBS's log message, this is a way for a test to write their own messages.
So it is intended that it looks different from MBS's internal logs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 58 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-Klbockq_rbcy-ZAVuFL:-KldxFCY1V63IwegsntB:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a509ff093c5044a4d0044c6124cc346fafc5f151/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L58)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Per https://source.android.com/source/code-style "Treat Acronyms As Words", should be `logWtf`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-Kldxs6j98FSCBaAwbD1:b4t8a9x) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This is not MBS's log message, this is a way for a test to write their own messages.
So it is intended that it looks different from MBS's internal logs.
</blockquote></details>

If that's the motivation, could we change the log tag to make this more clear? I think if you asked users to guess what the difference was between "MBS" and "com.google.android.mobly.snippet.bundled" log tags, they would be unlikely to come up with the real explanation as described here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-Kldys9lRnrBISed-0_S:bbjgnyc) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

If that's the motivation, could we change the log tag to make this more clear? I think if you asked users to guess what the difference was between "MBS" and "com.google.android.mobly.snippet.bundled" log tags, they would be unlikely to come up with the real explanation as described here.
</blockquote></details>

what should it be then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-KldyXHJo0QjNrISnTHv:bsn4ake) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what should it be then?
</blockquote></details>

MBSUser? MBSLogger?  MBSLogSnippet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-Kle-7KofvKa05OfG52e:b-mkaxbs) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

MBSUser? MBSLogger?  MBSLogSnippet?
</blockquote></details>

Those still coincide with "MBS".
I think Alex's point is that we should avoid referring to MBS in this tag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 25 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KlZXB1gdbvf48QDDiao:-KluYQuzr-N0pRwpcwLY:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/7dca3f082654daf3f8fbc4a8583fc7b29a169395/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Those still coincide with "MBS".
I think Alex's point is that we should avoid referring to MBS in this tag.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 27 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KluYehnDVUPiZCa8crI:-KluYehoCP5OtNLdFuhv:b-54nh9n) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/83c09779f62dcb81f581b193640a31cf008f6d68/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L27)):*
> ```Java
>     private String mTag = "MoblyTestLog";
> 
>     @Rpc(description = "Set the tag to use for logX Rpcs. Default is 'MBS'.")
> ```

Default value in comment no longer accurate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java, line 27 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-KluYehnDVUPiZCa8crI:-KluZ6SWiFod1uAibURx:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/83c09779f62dcb81f581b193640a31cf008f6d68/src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java#L27)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Default value in comment no longer accurate
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/52#-:-KluZKOMeOFdVxyx0mik:bnfp4nl)*

**Pull request merged**
