### PR TITLE
Initial audio playback functionality

### PR DESCRIPTION
**Pull request by dthkao**
Provides 3 methods: 
reset (brings the player back into idle mode)
playAudioFile (plays an audio file from external storage)
stop (stops the existing snippet playback)

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/62)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_Er5m10DKF6q5bqk:-Kmd_Er5m10DKF6q5bql:b-jpn2e5) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L29)):*
> ```Java
> import java.io.IOException;
> 
> /* Snippet class to control audio */
> ```

this class can technically play other types of media too right?
how about be more general in this docstring.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 39 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_YlFji71TGC4XtRZ:-Kmd_YlFji71TGC4XtR_:b295ynn) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L39)):*
> ```Java
> 
>   @Rpc(description = "Resets the snippet media player to an idle state.")
>   public void mediaReset() {
> ```

what's the difference between this and stop?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_Rm78r7uZU7twAM7:-Kmd_Rm78r7uZU7twAM8:b-uph7ts) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L61)):*
> ```Java
>   }
> 
>   @Rpc(description = "Stops playback.")
> ```

"Stops media playback"?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 62 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_PVqAv2jf84d17Xw:-Kmd_PVqAv2jf84d17Xx:bxnkm34) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L62)):*
> ```Java
> 
>   @Rpc(description = "Stops playback.")
>   public void mediaStop() throws IOException {
> ```

does this stop everything, regardless of the type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 44 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_mlBB55qvpl94Mpx:-Kmd_mlBB55qvpl94Mpy:b-8m8pl) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L44)):*
> mediaFile
`mediaFilePath` ?

Also, what does the path look like?
Accessing file on Android can be tricky due to the internal/external storage separation on some devices and the different APIs across versions for identifying the storage partitions.
Would be nice to try on a device that has sd card slot to be sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_Er5m10DKF6q5bqk:-Kmdm3f3oqMVWiQi2j_-:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L29)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this class can technically play other types of media too right?
how about be more general in this docstring.
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 39 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_YlFji71TGC4XtRZ:-KmdlPk5Zy017b2em4-0:bfagu6r) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L39)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what's the difference between this and stop?
</blockquote></details>

See state diagram here. https://developer.android.com/reference/android/media/MediaPlayer.html

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 44 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_mlBB55qvpl94Mpx:-Kmdl5FdW09a3u_8jOOc:b-v7qyih) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L44)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

> mediaFile
`mediaFilePath` ?

Also, what does the path look like?
Accessing file on Android can be tricky due to the internal/external storage separation on some devices and the different APIs across versions for identifying the storage partitions.
Would be nice to try on a device that has sd card slot to be sure.
</blockquote></details>

It works on any external storage path (hence the permission). Updated description.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_Rm78r7uZU7twAM7:-Kmdl44MIwn8S6LlhPCL:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

"Stops media playback"?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java, line 62 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-Kmd_PVqAv2jf84d17Xw:-KmdjLPQ2TBo5gZB3qiW:bns96c5) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/a45b655f94158521c9dabe20cdd65ee44724a7a2/src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java#L62)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

does this stop everything, regardless of the type?
</blockquote></details>

Yes. It brings the player to a stopped state: https://developer.android.com/reference/android/media/MediaPlayer.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/62#-:-Kn1W3Sb-3L1W_QTzRAg:bnfp4nl)*

**Pull request merged**
