### PR TITLE
Fixes in `serializeBluetoothDevice`.

### PR DESCRIPTION
**Pull request by xpconanfan**
* Replace ints with proper references.
* Remove fields not supported by API level 11.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/34)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 126 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9AtORQLfYX_r_kmBe:-Kh9AtORQLfYX_r_kmBf:brgqsuh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L126)):*
> ```Java
>     private JSONObject serializeBluetoothDevice(BluetoothDevice data) throws JSONException {
>         JSONObject result = new JSONObject();
>         result.put("Address", data.getAddress());
> ```

Could we have examples of serialized json structures for this and other types in the javadoc? I want to see if we have a consistent naming/capitalization scheme or not.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Kh9Ah8Gqglp1GITk9nU:by5yibv) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
> ```Java
>         switch (data.getBondState()) {
>             case BluetoothDevice.BOND_NONE:
>                 result.put("BondState", "NONE");
> ```

Per the name of the constant, this should be BOND_NONE?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Kh9Am5sljB8CH73RGSM:b-osrrur) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
> ```Java
>             result.put("Name", data.getName());
>         }
>         switch (data.getType()) {
> ```

Feel free to keep these and protect them behind an if statement that checks the current api version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 126 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9AtORQLfYX_r_kmBe:-Ki7JnjSNYqydPTYH8Zn:b-jhhn6k) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L126)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Could we have examples of serialized json structures for this and other types in the javadoc? I want to see if we have a consistent naming/capitalization scheme or not.
</blockquote></details>

This one seems pretty straightforward to figure out what the content is.
I'd rather not have java doc that explains straightforward code, that's just extra maintenance down the road for no benefit.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Ki7KJ-63gDSaDq3ZY87:b-1yhga0) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Per the name of the constant, this should be BOND_NONE?
</blockquote></details>

Not a bit fan of repeating the "BOND"_ though, since the name of the field clearly states it

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Ki7KEcAT6QrNnDWX6oT:btr2ey7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Feel free to keep these and protect them behind an if statement that checks the current api version.
</blockquote></details>

What do you mean by that? which version do we need to check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 126 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9AtORQLfYX_r_kmBe:-Ki7LpuyfGXh7J7xz_T-:bylqmx7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L126)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

This one seems pretty straightforward to figure out what the content is.
I'd rather not have java doc that explains straightforward code, that's just extra maintenance down the road for no benefit.
</blockquote></details>

I see; what would be the preferred way to see if we have a consistent naming/capitalization scheme then?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Ki7M2iv7-78jRSE0S45:b-gjpmyf) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Not a bit fan of repeating the "BOND"_ though, since the name of the field clearly states it
</blockquote></details>

You're not a fan of Android API's chosen names for these constants? I agree but I don't think that's our choice to make.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Ki7M8jOS6Mck2Jk7Kq3:by88anb) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

What do you mean by that? which version do we need to check?
</blockquote></details>

```
if (Build.VERSION.SDK_INT >= 18) {
  switch (data.getType()) {
...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 126 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9AtORQLfYX_r_kmBe:-Ki7YiZATwcMilZoDgXi:b-rmlje0) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L126)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I see; what would be the preferred way to see if we have a consistent naming/capitalization scheme then?
</blockquote></details>

I don't know a good way other than checking in code review when something is added.
We probably have some inconsistency right now coming from the GSON serialization, which should probably be fixed in a separate PR?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Ki7ZMZEf5HarhS2XBCV:b-s1h5ud) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

You're not a fan of Android API's chosen names for these constants? I agree but I don't think that's our choice to make.
</blockquote></details>

It's NBD, but I do want to point out that these are not 1:1 mapping to Android APIs though.

Like Android API returns SSID wrapped with quotation marks, and we trim off the quotation marks because nobody uses SSID that way.

Because of the inconsistencies and bad designs in Android APIs, we should probably be flexible and follow some commons sense as opposed to blindly following Android API design.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Ki7YX40jHS56EVV9NMt:bxzzczr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

```
if (Build.VERSION.SDK_INT >= 18) {
  switch (data.getType()) {
...
```
</blockquote></details>

Our min sdk version is 11, so I can't use getType unless I change min sdk version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Ki8UMTF8b8futarx4KG:b-ezp51x) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It's NBD, but I do want to point out that these are not 1:1 mapping to Android APIs though.

Like Android API returns SSID wrapped with quotation marks, and we trim off the quotation marks because nobody uses SSID that way.

Because of the inconsistencies and bad designs in Android APIs, we should probably be flexible and follow some commons sense as opposed to blindly following Android API design.
</blockquote></details>

For input, sure, we can be more liberal in what we accept. But here we're directly outputting one of the android API objects, but we're arbitrarily renaming some fields in a way people don't expect.

Look at it this way: if people want to find out what wifiConnectSimple does, they'll look at our docs. But if they want to find out what's inside a BluetoothDevice object, they'll look at the Android docs. And those docs will claim it has constants that we've renamed.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Ki8UjT845W47YDVd5t9:b-6suv0k) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Our min sdk version is 11, so I can't use getType unless I change min sdk version
</blockquote></details>

I'm not sure what you mean by "can't use getType". Due to the if statement that checks for API >18, `getType` will never get executed on a device with OS version <18 so **not** be used. `minSdkVersion` isn't the right constant to be looking at here, `compileSdkVersion` affects what SDK you build with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Ki8t1tCREXgtL4TV5wn:bqf9mg7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

For input, sure, we can be more liberal in what we accept. But here we're directly outputting one of the android API objects, but we're arbitrarily renaming some fields in a way people don't expect.

Look at it this way: if people want to find out what wifiConnectSimple does, they'll look at our docs. But if they want to find out what's inside a BluetoothDevice object, they'll look at the Android docs. And those docs will claim it has constants that we've renamed.
</blockquote></details>

I don't mean input, we trim the SSID in the serialized `WifiConfiguration` and `WifiInfo` objects in this class.

As we've decided in the wifiConnect discussion, we don't follow Android APIs word by word. And I think it's reasonable to assume people can understand what `"BondState": "BONDING"` means if we don't use "BOND_BONDING".

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Ki8thePLPfPeudBSX8F:b-w9ists) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I'm not sure what you mean by "can't use getType". Due to the if statement that checks for API >18, `getType` will never get executed on a device with OS version <18 so **not** be used. `minSdkVersion` isn't the right constant to be looking at here, `compileSdkVersion` affects what SDK you build with.
</blockquote></details>

Android studio would give red underscored alert for the line


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by adorokhine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Ki8utCPt4Nugvybf5Bi:b4vlscu) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I don't mean input, we trim the SSID in the serialized `WifiConfiguration` and `WifiInfo` objects in this class.

As we've decided in the wifiConnect discussion, we don't follow Android APIs word by word. And I think it's reasonable to assume people can understand what `"BondState": "BONDING"` means if we don't use "BOND_BONDING".
</blockquote></details>

Not following android APIs means we can make utility functions and wrap behaviour in more logical chunks, not that we can just arbitrarily rename constants in data structures because we don't like the Android name. If we came up with our own way of representing the return value of a bluetooth lookup which was easier to deal with, that would be totally fine, but we're not --- we're just serializing an existing data structure except for one particular field we've decided to arbitrarily rename. Same for WifiConfig; if we're serializing it we should just be passing back exactly what the OS gives us unless we want to start calling it something else and putting more/better stuff in it.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Ki8vkuWMY-_HUfTzw_j:b6hnpne) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Android studio would give red underscored alert for the line


</blockquote></details>

Looks from that screenshot that it's not in an `if (Build.VERSION.SDK_INT >= 18) {` block like I suggested above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-Ki8wFYotkAfCtEh4kmO:b-nzrsjw) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Not following android APIs means we can make utility functions and wrap behaviour in more logical chunks, not that we can just arbitrarily rename constants in data structures because we don't like the Android name. If we came up with our own way of representing the return value of a bluetooth lookup which was easier to deal with, that would be totally fine, but we're not --- we're just serializing an existing data structure except for one particular field we've decided to arbitrarily rename. Same for WifiConfig; if we're serializing it we should just be passing back exactly what the OS gives us unless we want to start calling it something else and putting more/better stuff in it.
</blockquote></details>

I disagree. The purpose of the MBS is to facilitate testing, and we are not obligated to follow every name in Android API.

In the case of SSID:
Trimming SSID helps a lot in testing. Otherwise all tests will need to trim those themselves.
Nobody uses SSID with quotation marks and we don't need to input SSID with quotation marks to Android either. It is actually a bad design in Android API that these quotation marks around SSIDs are inconsistent within Android.

For another example, if the mac address were serialized as is, it's an integer which is not very useful for most users. We translate it to the string form during serialization so it can be actually useful in tests.

In the case of bond state, the purpose here is to communicate the bond state, not to communicate the name of the Android variable name.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-Ki8w1dUtlz5icB6hZCu:bjo7uie) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Looks from that screenshot that it's not in an `if (Build.VERSION.SDK_INT >= 18) {` block like I suggested above?
</blockquote></details>

The alert is there regardless of being in an if or not.
It doesn't affect compilation, but we'd have to live with this alert from now on.
Is that something we want to do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-KiBFIwde2A7TXZWbaTb:bb7z4lu) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

The alert is there regardless of being in an if or not.
It doesn't affect compilation, but we'd have to live with this alert from now on.
Is that something we want to do?
</blockquote></details>

I just tried it, this is not true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-KiBFyfudzsxOWdT-u9C:b99f110) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I just tried it, this is not true.
</blockquote></details>



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
It was for me on Mac.

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-KiBS3KOAh3rRf5tHujZ:b-wy3j83) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>


</blockquote></details>

An alternative would be to push the getType switch into it's own method and mark that with @TargetApi(18)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-KiCLpTk7BcrD9t3k0BI:bmtyqws) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

An alternative would be to push the getType switch into it's own method and mark that with @TargetApi(18)
</blockquote></details>

I figured out why.
I'm using the version macros in Build. K was 19, so I thought Jelly bean was 18, and it turns that that's not the case... sorry
Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 145 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Am5sljB8CH73RGSL:-KiE8W3167X1L-T2zGfJ:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/5b20052d9aac1fcd5c166f725ef5bc47bb6e59e8/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L145)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I figured out why.
I'm using the version macros in Build. K was 19, so I thought Jelly bean was 18, and it turns that that's not the case... sorry
Will fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Ping

**Comment by adorokhine** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-KilD1KXB5LqgB5NG_od:bba60c3) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I disagree. The purpose of the MBS is to facilitate testing, and we are not obligated to follow every name in Android API.

In the case of SSID:
Trimming SSID helps a lot in testing. Otherwise all tests will need to trim those themselves.
Nobody uses SSID with quotation marks and we don't need to input SSID with quotation marks to Android either. It is actually a bad design in Android API that these quotation marks around SSIDs are inconsistent within Android.

For another example, if the mac address were serialized as is, it's an integer which is not very useful for most users. We translate it to the string form during serialization so it can be actually useful in tests.

In the case of bond state, the purpose here is to communicate the bond state, not to communicate the name of the Android variable name.
</blockquote></details>

This isn't a part of the API; the purpose of this class is to serialize an existing object for transmission to python. If you want to rewrite the constant ints to strings just so you don't have to port the constant definitions into every util, that's ok, I could go either way on that since the constants aren't defined in python. But we shouldn't be arbitrarily renaming constants as part of serializing an object. If someone wants to know what a BluetoothDevice object contains, they'd look at the Android documentation, but that documentation wouldn't be valid here since we've changed the object.

If you think BluetoothDevice is a difficult object to interact with because of this reason, feel free to make your own type of object (with documentation) and call that a new, improved API, which you can serialize any way you like. That'd be fine by me. But right now the purpose of this method is just to serialize an existing object, so changing it implicitly as part of this process seems like a bad idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 129 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9Ah8Fx57VHdxavrSH:-KilN3-CEpi9iFE7437I:b-gcjqfk) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L129)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This isn't a part of the API; the purpose of this class is to serialize an existing object for transmission to python. If you want to rewrite the constant ints to strings just so you don't have to port the constant definitions into every util, that's ok, I could go either way on that since the constants aren't defined in python. But we shouldn't be arbitrarily renaming constants as part of serializing an object. If someone wants to know what a BluetoothDevice object contains, they'd look at the Android documentation, but that documentation wouldn't be valid here since we've changed the object.

If you think BluetoothDevice is a difficult object to interact with because of this reason, feel free to make your own type of object (with documentation) and call that a new, improved API, which you can serialize any way you like. That'd be fine by me. But right now the purpose of this method is just to serialize an existing object, so changing it implicitly as part of this process seems like a bad idea.
</blockquote></details>

ok, that's fair. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, line 126 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-Kh9AtORQLfYX_r_kmBe:-KilXHIjaPsXBVYOgGwt:b-kjakzk) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/1a24cf22ee04bea67874cc080945b43ae85917ca/src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java#L126)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I don't know a good way other than checking in code review when something is added.
We probably have some inconsistency right now coming from the GSON serialization, which should probably be fixed in a separate PR?
</blockquote></details>

sg, filed a bug for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/34#-:-KilXLw6FbVN7nZmtuHZ:bnfp4nl)*

**Pull request merged**
