### PR TITLE
Add basic Bluetooth pairing and A2DP connection features.

### PR DESCRIPTION
**Pull request by xpconanfan**
* Add support for pairing/unpairing a device.
    * Add support for connecting with A2DP profile.
    * Reorganize Bluetooth related snippets for future expansion of profile support.
    * Use Bundle instead of JSONObject for BluetoothDevice serialization.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/54)

### CODE REVIEW

**Comment by dthkao** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 49 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4qAFqQYKKhTm-m7ba:-Km4qAFqQYKKhTm-m7bb:b-xb2gvh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L49)):*
> ```Java
> 
>     private final Context mContext;
>     private static BluetoothAdapter mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
> ```

why not final?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 214 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4rH8FAcDtNOcYzZjy:-Km4rH8GGZnDeePR-vBs:b4jyfoh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L214)):*
> ```Java
> 
>     @Rpc(description = "Pair with a bluetooth device.")
>     public void btPairDevice(String deviceAddress) throws Throwable {
> ```

btPairDeviceByAddress? same for unpair.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 293 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4qtH2SXLc-gDo1lyC:-Km4qtH2SXLc-gDo1lyD:bpl29ko) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L293)):*
> ```Java
>                 BluetoothDevice device =
>                         (BluetoothDevice) intent.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);
>                 mDiscoveryResults.put(device.getAddress(), device);
> ```

Any reason we need to use the address instead of the name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 49 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4qAFqQYKKhTm-m7ba:-Km4yQzTm-fbvrPf71JO:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L49)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

why not final?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 214 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4rH8FAcDtNOcYzZjy:-Km4zClZ8Oy1dgWLghxC:bile02s) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L214)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

btPairDeviceByAddress? same for unpair.
</blockquote></details>

Since every rpc that takes a BluetoothDevice would use address, i'd prefer to not repeat "ByAddress" in all these rpcs.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 293 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4qtH2SXLc-gDo1lyC:-Km4yU42doS5eQJOdIRh:b5dznr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L293)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Any reason we need to use the address instead of the name?
</blockquote></details>

Name can be set to anything and has a high chance of collision.
E.g. Phones of the same model usually have the same default bt name.

Address is set in hw and unique.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54)*

**Comment by dthkao** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 214 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4rH8FAcDtNOcYzZjy:-Km53fQiF1516_10qsGf:bx9dhsl) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L214)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Since every rpc that takes a BluetoothDevice would use address, i'd prefer to not repeat "ByAddress" in all these rpcs.
</blockquote></details>

We return lists of BluetoothDevices (Bundles?) right? That would seem a more natural RPC argument. no added processing client side.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 293 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4qtH2SXLc-gDo1lyC:-Km52pG3M_z8H18LwVMF:bk7adpe) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L293)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Name can be set to anything and has a high chance of collision.
E.g. Phones of the same model usually have the same default bt name.

Address is set in hw and unique.
</blockquote></details>

I appreciate that address is more accurate, but users generally see and select on names (even with the possibility of collisions).  Do the keys here ever make it back to the user?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 214 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4rH8FAcDtNOcYzZjy:-Km55dUknXPjS1Abj_k5:b-l0162c) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L214)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

We return lists of BluetoothDevices (Bundles?) right? That would seem a more natural RPC argument. no added processing client side.
</blockquote></details>

Not sure what this is about. Can you clarify the ask?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 293 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4qtH2SXLc-gDo1lyC:-Km55hRY71nBmEf4nOlb:b-5btort) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L293)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I appreciate that address is more accurate, but users generally see and select on names (even with the possibility of collisions).  Do the keys here ever make it back to the user?
</blockquote></details>

These are meant for use in tests, not regular consumers.

It is impractical to use name as the device's identifier as collisions would be too interruptive.
e.g. In a non-shielded env, say at one's desk in office, it could easily find multiple devices of the same name, like "Nexus 6P". An rpc that takes a name id would be useless for tests in this case.

Also a bt device can have no name at all, and tests still need to be able to connect to such devices.
Using the name as device identifier is not feasible per bt standard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54)*

**Comment by dthkao** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 118 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km7VYttcjWwPYDqGWxd:-Km7VYttcjWwPYDqGWxe:bavs4fg) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L118)):*
> ```Java
>                 "Get bluetooth discovery results, which is a list of serialized BluetoothDevice objects."
>     )
>     public ArrayList<Bundle> btGetCachedScanResults() {
> ```

List<Bundle>?  same below?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 214 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4rH8FAcDtNOcYzZjy:-Km7Uq2LwUgrygue4P2X:bjzpru5) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L214)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Not sure what this is about. Can you clarify the ask?
</blockquote></details>

I mean that because bt(DiscoverAndGetResults|GetPairedDevices) return List<Bundle> with a Bundle serializing a BluetoothDevice object, there should be an RPC that takes that Bundle right back as an argument. Instead we are assuming the default flow to be btGet... > iterate and extract the address > btPairDevice(address).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54)*

**Comment by xpconanfan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 118 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km7VYttcjWwPYDqGWxd:-Km7eLvAhqeW1evXCb1t:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L118)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

List<Bundle>?  same below?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, line 214 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-Km4rH8FAcDtNOcYzZjy:-Km7b8mnVogwHiQ6gDsW:b-ze7qsz) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/30df8e424aab30a4a82d5d057eb4f00c2f10ceff/src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java#L214)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I mean that because bt(DiscoverAndGetResults|GetPairedDevices) return List<Bundle> with a Bundle serializing a BluetoothDevice object, there should be an RPC that takes that Bundle right back as an argument. Instead we are assuming the default flow to be btGet... > iterate and extract the address > btPairDevice(address).
</blockquote></details>

Snippet lib does not support `Bundle` as input param, so it's infeasible today.

Also all we really need is the address, we don't need the other stuff in the serialized BluetoothDevice for these calls.
So instead of forcing the test to cache the whole thing, it's probably easier to just use the address when writing the test.

For a purely serializable data object, like `WifiConfiguration`, maybe it makes sense, because the obj has no internal state that Android utilizes. But for objects like `BluetoothDevice`, which can't be serialized because it has states internal to Android OS, taking a Bundle in rpcs seems to create more room for error and confusion without clear benefits.

E.g. if the rpcs took Bundle and the test altered the non-address fields serialized Bundle and passed it back, what's the behavior? Do we need to verify that every single field matches before we proceed? Or do we just proceed as long as the address is a match?

If a test has the address, it can call the Rpcs; if the test the serialized Bundle, it can also call rpcs since the address is known. So this way probably works ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/54#-:-KmSNAXaSHWqITr9Zhhj:bnfp4nl)*

**Pull request merged**
