### PR TITLE
Adding content sync controls to AccountSnippet.

### PR DESCRIPTION
**Pull request by dthkao**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/25)

### CODE REVIEW

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 63 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsOzncJURHEqWX8cVK:-KdsOzndO-xQaIgFesaz:bk3lkr) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L63)):*
> ```Java
>     private final List<Object> mSyncStatusObserverHandles;
> 
>     private Map<String, Set<String>> mWhitelist;
> ```

mSyncWhitelist?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 132 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsP9upNsDoWZjUdCse:-KdsP9uq83JYMDJNAKdL:bj0zzn6) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L132)):*
> ```Java
>                                 }
>                                 Log.i(
>                                         "Attempt to sync account "
> ```

Does this print a reasonable number of logs? I tried to do this originally and it was really spammy... maybe we could only log once per account-authority pair if it's too bad?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 136 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsPJ9kHTtfabkfctEZ:-KdsPJ9kHTtfabkfctE_:binwdnb) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L136)):*
> ```Java
>                                                 + ", adapter "
>                                                 + adapter.authority
>                                                 + " detected! Disabling.");
> ```

Not necessarily "disabling" depending on whitelist

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 157 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsPYRMnG2ZGiw6vfnK:-KdsPYRNjQElQ4fDe3I3:becw6dd) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L157)):*
> ```Java
>      */
>     private boolean isAdapterWhitelisted(String username, String authority) {
>         if (mWhitelist.containsKey(username)) {
> ```

Might as well avoid the double lookup:
```
Set<String> whitelistedProviders = mWhitelist.get(username)
if (whitelistedProviders != null) {
  return whitelistedProviders.contains(authority);
}
return false;
```

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 198 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsQ4bedjyfCSVa_H1A:-KdsQ4bedjyfCSVa_H1B:bx89v48) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L198)):*
> ```Java
>         }
>         // Add to the whitelist
>         if (mWhitelist.containsKey(username)) {
> ```

This is going to be running on a different thread than the readers which are going to be pulling from the list, so needs to either use ConcurrentHashMap and separate locks on the sets, or a big lock over everything, or a ReentrantReadWriteLock, or some other kind of locking.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java, line 78 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsQlHhDROdburMjCKI:-KdsQlHhDROdburMjCKJ:buh8lea) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java#L78)):*
> ```Java
>     public void muteAll() throws Exception {
>         /* Get numStreams from AudioSystem through reflection. If for some reason this fails,
>         calling muteAll will throw. */
> ```

I think the style guide suggests this type of comment should have a * for every line right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by dthkao** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 63 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsOzncJURHEqWX8cVK:-KdvtjK3fAXmz-M3NBt2:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L63)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

mSyncWhitelist?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 132 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsP9upNsDoWZjUdCse:-KdvtkcUDdp4OUYS1lMQ:bbt0x3u) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L132)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Does this print a reasonable number of logs? I tried to do this originally and it was really spammy... maybe we could only log once per account-authority pair if it's too bad?
</blockquote></details>

It *is* spammy. How would you propose to log just once per account-authority pair? track the disabled ones?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 136 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsPJ9kHTtfabkfctEZ:-KdvuAqYHk6pVTdfXVKl:bcadwys) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L136)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Not necessarily "disabling" depending on whitelist
</blockquote></details>

Whoops, moved it below the whitelist filter.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 157 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsPYRMnG2ZGiw6vfnK:-KdvuP9UZpQICZGlcIFI:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L157)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Might as well avoid the double lookup:
```
Set<String> whitelistedProviders = mWhitelist.get(username)
if (whitelistedProviders != null) {
  return whitelistedProviders.contains(authority);
}
return false;
```
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 198 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsQ4bedjyfCSVa_H1A:-Kdxx5ShyZ0zqfSfsetr:b-3o2xcp) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L198)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This is going to be running on a different thread than the readers which are going to be pulling from the list, so needs to either use ConcurrentHashMap and separate locks on the sets, or a big lock over everything, or a ReentrantReadWriteLock, or some other kind of locking.
</blockquote></details>

Went with a biggish lock. PTAL.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java, line 78 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsQlHhDROdburMjCKI:-KdvuvUO1YGt6uX4cW7_:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java#L78)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I think the style guide suggests this type of comment should have a * for every line right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 132 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsP9upNsDoWZjUdCse:-Kdyey9Hjl5gvOwCpUZi:bjquet7) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L132)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

It *is* spammy. How would you propose to log just once per account-authority pair? track the disabled ones?
</blockquote></details>

One option would be to throw everything we logged into a big set and only do the log if the entry was successfully added for the first time (which the return value of put() tells you).

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 198 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsQ4bedjyfCSVa_H1A:-KdyfIaw5sqELgCruJA3:b6fylge) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L198)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Went with a biggish lock. PTAL.
</blockquote></details>

1. Inconsistent synchronization on mSyncWhitelist (isAdapterWhitelisted doesn't use it, but everything else does, and I think isAdapterWhitelisted's lookup could still conflict with writes)
2. Could you synchronize on `this` instead of mSyncWhitelist? Otherwise it's confusing why you'd need to externally synchronize an already synchronized map. Alternatively, could you remove the wrapper of synchronizedmap and keep the external sync on mSyncWhitelist?
3. Why do you need to wrap this in a synchronized map? It seems to be read under the map's lock by the snippet anyway...

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 64 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-Kdyes6Y_QEudH35qpUi:-Kdyes6ZkCv2lCmjlh6y:b-b8x95r) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/fd359d47d778970602bd903e272a9b3b11074afc/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L64)):*
> ```Java
>     private final List<Object> mSyncStatusObserverHandles;
> 
>     private Map<String, Set<String>> mSyncWhitelist;
> ```

Should be final

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by dthkao** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 132 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsP9upNsDoWZjUdCse:-KeAjQ7XuJPtZtWshZd8:b-tg46f3) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L132)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

One option would be to throw everything we logged into a big set and only do the log if the entry was successfully added for the first time (which the return value of put() tells you).
</blockquote></details>

The thing is that set could change after calling startSync or stopSync.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 198 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsQ4bedjyfCSVa_H1A:-KdyrVGB8ruvBoR8iAKs:b11pn51) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L198)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

1. Inconsistent synchronization on mSyncWhitelist (isAdapterWhitelisted doesn't use it, but everything else does, and I think isAdapterWhitelisted's lookup could still conflict with writes)
2. Could you synchronize on `this` instead of mSyncWhitelist? Otherwise it's confusing why you'd need to externally synchronize an already synchronized map. Alternatively, could you remove the wrapper of synchronizedmap and keep the external sync on mSyncWhitelist?
3. Why do you need to wrap this in a synchronized map? It seems to be read under the map's lock by the snippet anyway...
</blockquote></details>

Switched to ReentrantReadWriteLock anyway, but re: 1 and 2 SynchronizedMap keeps the individual calls synchronized, while start/stopSync (and isAdapterWhitelisted) have multiple actions. 

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 64 at r2](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-Kdyes6Y_QEudH35qpUi:-KeAjMHBr4t5fAzgMheW:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/fd359d47d778970602bd903e272a9b3b11074afc/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L64)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Should be final
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by dthkao** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 132 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KdsP9upNsDoWZjUdCse:-KeAnSIMxnMtqlFLQpcm:bopj3zm) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/b5a8981b164314638ade8757254fbdb90bed88d3/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L132)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

The thing is that set could change after calling startSync or stopSync.
</blockquote></details>

Moved this to updateSync, and added logic to avoid unecessary updates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by adorokhine** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 155 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeFNgtHds2KVCBMe3xp:-KeFNgtIi7bpMrQN7JDG:b-aps8j2) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/3922fbc9256d78622fdc30fa2abc6be538865005/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L155)):*
> ```Java
>     private boolean isAdapterWhitelisted(String username, String authority) {
>         boolean result = false;
>         mLock.readLock().lock();
> ```

Locks like this should always be locked in a try...finally pattern to avoid permanently keeping locks locked in the case of exceptions (here and elsewhere)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by dthkao** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 155 at r3](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeFNgtHds2KVCBMe3xp:-KeFRz0wyTtvN6YPc9pX:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/3922fbc9256d78622fdc30fa2abc6be538865005/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L155)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Locks like this should always be locked in a try...finally pattern to avoid permanently keeping locks locked in the case of exceptions (here and elsewhere)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 156 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeFXpd1fhGq3myKxTcM:-KeFXpd5fe9WdYzY6L9m:b-9b2teb) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/43ceb4ddb1c03a7da785908b47cf7bd693039fc9/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L156)):*
> ```Java
>         boolean result = false;
>         try {
>             mLock.readLock().lock();
> ```

This line should be outside the try. If we fail to lock the lock, we shouldn't be trying to unlock it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by dthkao** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 156 at r4](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeFXpd1fhGq3myKxTcM:-KeFZ7S8WGi5YmHZvQKk:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/43ceb4ddb1c03a7da785908b47cf7bd693039fc9/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L156)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This line should be outside the try. If we fail to lock the lock, we shouldn't be trying to unlock it. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by adorokhine** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 71 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeIE2Kud2lJ68JKaLKG:-KeIE2KvR4MCfnZE-99X:b-jgpu0l) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/668755d97a9686ef2c177f876e496132c329c534/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L71)):*
> ```Java
>         mAccountManager = AccountManager.get(context);
>         mSyncStatusObserverHandles = new LinkedList<>();
>         mSyncWhitelist = new HashMap<String, Set<String>>();
> ```

Does diamond operator (new HashMap<>) work here instead?

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 218 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeIEmnFBeRk0-tBWoxG:-KeIEmnGw-zL75pwQaTp:b-5k0u7u) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/668755d97a9686ef2c177f876e496132c329c534/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L218)):*
> ```Java
>             }
>             // Update the Sync settings
>             for (SyncAdapterType adapter : ContentResolver.getSyncAdapterTypes()) {
> ```

Does this part have to be done under the write lock? you don't seem to be reading or writing from mSyncWhitelist anymore by the time you get here... same below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by dthkao** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 71 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeIE2Kud2lJ68JKaLKG:-KeKQ98b5gLqoyQ_cP4Y:b-896fix) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/668755d97a9686ef2c177f876e496132c329c534/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L71)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Does diamond operator (new HashMap<>) work here instead?
</blockquote></details>

Done.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 218 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeIEmnFBeRk0-tBWoxG:-KeKPU-jX3LsemQ9SgIS:bgwou8w) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/668755d97a9686ef2c177f876e496132c329c534/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L218)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Does this part have to be done under the write lock? you don't seem to be reading or writing from mSyncWhitelist anymore by the time you get here... same below.
</blockquote></details>

We don't need to be writing but I'm also using (abusing?) it to gate the updateSync calls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by adorokhine** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 218 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeIEmnFBeRk0-tBWoxG:-KeKSjz9uZOfIzEJr2M4:b9pz090) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/668755d97a9686ef2c177f876e496132c329c534/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L218)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

sg, can you add a comment to updateSync's doc that it must always be called under the write lock to avoid flapping between the getSyncAutomatically and setSyncAutomatically calls?
</blockquote></details>

Wait, if that's the case, why aren't you locking access to it in addAccount?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by dthkao** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 218 at r5](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeIEmnFBeRk0-tBWoxG:-KeKSdQ6UNq4mjVXnsbA:b-kb1smt) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/668755d97a9686ef2c177f876e496132c329c534/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L218)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Wait, if that's the case, why aren't you locking access to it in addAccount?
</blockquote></details>

Added the writelock in addAccount. This actually makes the readlock in isAdapterWhitelisted unnecessary, but keeping it there just in case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 137 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeN5i5gnh7BtFbC_x9v:-KeN5i5gnh7BtFbC_x9w:bmkugb4) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c814ca69c155708e0336d0bf751ffbfebb76f434/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L137)):*
> ```Java
>                                 mLock.writeLock().lock();
>                                 try {
>                                     if (!isAdapterWhitelisted(username, adapter.authority)) {
> ```

Doesn't have to change, just for my own undestanding: does isAdapterWhitelisted also have to be called under the write lock? If so it should have a comment explaining why... otherwise how come it's being run under lock here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-:-KeN5fJSFa4CjoE9uDoL:bnfp4nl)*

**Comment by dthkao** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 137 at r6](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-KeN5i5gnh7BtFbC_x9v:-KeS-3cF9CCykyKN18Z9:bonbfe5) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/c814ca69c155708e0336d0bf751ffbfebb76f434/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L137)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Doesn't have to change, just for my own undestanding: does isAdapterWhitelisted also have to be called under the write lock? If so it should have a comment explaining why... otherwise how come it's being run under lock here?
</blockquote></details>

Added a comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/25#-:-KeWGELhnzHEOC87kp07:bnfp4nl)*

**Pull request merged**
