### PR TITLE
Add functionality to specify timeout for waitForSms.

### PR DESCRIPTION
**Pull request by dthkao**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/95)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 122 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/95#-LC5EM4w0ybaeQ_smzH8:-LC5EM4x-mlp6n2Rzs8i:bb77kfm) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/93a06168f41d3872707d6271a3f8dd9da8cf70a6/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L122)):*
> ```Java
>         SmsReceiver receiver = new SmsReceiver(mContext, callbackId);
>         mContext.registerReceiver(receiver, new IntentFilter(Intents.SMS_RECEIVED_ACTION));
>         return Utils.waitForSnippetEvent(callbackId, SMS_RECEIVED_EVENT_NAME, timeoutMillis)
> ```

Should we change the timeout param type to be Long in Utils?...

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/95)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 122 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/95#-LC5EM4w0ybaeQ_smzH8:-LC5IyHWENSgAruEJuSU:b-kjsgwh) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/93a06168f41d3872707d6271a3f8dd9da8cf70a6/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L122)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Should we change the timeout param type to be Long in Utils?...
</blockquote></details>

Long or long? Either way your call. I think using int is less conventional, but tops out near a 600 hour timeout?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/95)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 122 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/95#-LC5EM4w0ybaeQ_smzH8:-LC5Vbo71IniFJcw1PQK:bp1argv) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/93a06168f41d3872707d6271a3f8dd9da8cf70a6/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L122)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Long or long? Either way your call. I think using int is less conventional, but tops out near a 600 hour timeout?
</blockquote></details>

Looks like Util is inconsistent about it...
I have no strong preference for long/Long.
I checked some guava code and they seem to use `long`

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/95)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, line 122 at r1](https://reviewable.io/reviews/google/mobly-bundled-snippets/95#-LC5EM4w0ybaeQ_smzH8:-LC5gesA2s2NtypAbzO5:bzdgouo) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/93a06168f41d3872707d6271a3f8dd9da8cf70a6/src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java#L122)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Looks like Util is inconsistent about it...
I have no strong preference for long/Long.
I checked some guava code and they seem to use `long`
</blockquote></details>

Let's tackle this in another PR. since it'll expand the scope of this then?

---


*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/95)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/95#-:-LC5pzzp9DGjeYzyPcOW:bnfp4nl)*

**Pull request merged**
