### PR TITLE
Squash "serializable class has no definition of serialVersionUID" warning.

### LINKED ISSUE #36: Build warnings in exception classes
```
/Users/angli/Developer/mobly-bundled-snippets/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java:55: warning: [serial] serializable class AccountSnippetException has no definition of serialVersionUID
    private static class AccountSnippetException extends Exception {
                   ^
/Users/angli/Developer/mobly-bundled-snippets/src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java:36: warning: [serial] serializable class BluetoothAdapterSnippetException has no definition of serialVersionUID
    private static class BluetoothAdapterSnippetException extends Exception {
                   ^
/Users/angli/Developer/mobly-bundled-snippets/src/main/java/com/google/android/mobly/snippet/bundled/utils/ApiVersionException.java:4: warning: [serial] serializable class ApiVersionException has no definition of serialVersionUID
public class ApiVersionException extends Exception {
       ^
```

### PR DESCRIPTION
**Pull request by adorokhine**
Fixes #36.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-bundled-snippets/37)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 56 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37#-Ki7Y2JkKkGIysBymDVg:-Ki7Y2JkKkGIysBymDVh:bn2nb8w) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32b546f6ca8e3c034cedc29a76a8e3a2ad3c7ee5/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L56)):*
> ```Java
> 
>     private static class AccountSnippetException extends Exception {
>         private static final long serialVersionUID = 1;
> ```

what's the pros/cons between adding this with an arbitrary value and using `@SuppressWarning`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37)*

**Comment by adorokhine** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 56 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37#-Ki7Y2JkKkGIysBymDVg:-Ki7Zei9mcIIEP628H5G:b10aot1) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32b546f6ca8e3c034cedc29a76a8e3a2ad3c7ee5/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L56)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

what's the pros/cons between adding this with an arbitrary value and using `@SuppressWarning`?
</blockquote></details>

Can you explain what you mean by "arbitrary value"? The `1` is not arbitrary, it a version number which indicates the version of serialization logic implemented in this class. It should be incremented any time the serialization/deserialization logic is changed in an incompatible way so that Java knows not to try and deserialize old bundles using incompatible new logic.

The pros would be that this class could be serialized if ever the need to do so came up. (all exceptions are supposed to be serializable).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37)*

**Comment by xpconanfan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 56 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37#-Ki7Y2JkKkGIysBymDVg:-Ki7hWoZPn9w5KkVOJeI:b-1tm6zp) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32b546f6ca8e3c034cedc29a76a8e3a2ad3c7ee5/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L56)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Can you explain what you mean by "arbitrary value"? The `1` is not arbitrary, it a version number which indicates the version of serialization logic implemented in this class. It should be incremented any time the serialization/deserialization logic is changed in an incompatible way so that Java knows not to try and deserialize old bundles using incompatible new logic.

The pros would be that this class could be serialized if ever the need to do so came up. (all exceptions are supposed to be serializable).
</blockquote></details>

Hmm, if that's the case, you'd probably want to change the one in `WifiManagerSnippet` as well...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37)*

**Comment by adorokhine** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 56 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37#-Ki7Y2JkKkGIysBymDVg:-Ki8U2xqQri-mHqGcVy2:b61z4hc) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32b546f6ca8e3c034cedc29a76a8e3a2ad3c7ee5/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L56)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, if that's the case, you'd probably want to change the one in `WifiManagerSnippet` as well...
</blockquote></details>

Not sure what you mean; this CL adds a similar line to `WifiManagerSnippet` as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, line 56 at r1](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37#-Ki7Y2JkKkGIysBymDVg:-Ki8UPpsWW52m13YDXAr:b-sjtra6) ([raw file](https://github.com/google/mobly-bundled-snippets/blob/32b546f6ca8e3c034cedc29a76a8e3a2ad3c7ee5/src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java#L56)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Not sure what you mean; this CL adds a similar line to `WifiManagerSnippet` as well?
</blockquote></details>

Oops. Sorry i was confused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37#-:-Ki8UU9uToKNT1ypY6QU:bnfp4nl)*

**Comment by adorokhine** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-bundled-snippets/37)*

**Pull request merged**
